// ============================================================================
// Contenido profundo del curso de Comunicación / Lenguaje.
//
// Estos archivos PROFUNDIZAN la estructura de assets/js/cursos-data.js. La
// union es por posicion: modulos[0] es el primer modulo del curso y
// lecciones[3] es su cuarta leccion. Si aqui hay mas modulos o mas lecciones
// de las que existen, se anaden como nuevas y necesitan traer titulo.
// ============================================================================
CONTENIDO["comunicacion"] = {
  modulos: [
    {
      lecciones: [
        {
          objetivo: "Distinguir las funciones del lenguaje y reconocer cual domina en un texto, porque de eso depende como hay que leerlo y como hay que escribirlo.",
          teoria: "## Que son las funciones del lenguaje\nCuando alguien dice algo, siempre hace al menos dos cosas a la vez: expresa lo que siente y, a la vez, se dirige a alguien para conseguir un efecto. Cada una de esas acciones es una **funcion del lenguaje**.\n\nLa funcion dominante es la que manda en el texto. Las demas pueden estar presentes, pero en segundo plano.\n\n## Las cinco funciones\n1. **Emotiva o expresiva**: el emisor manda. Predominan los adjetivos, los adjetivaciones y los signos de admiracion.\n2. **Referencial o informativa**: el contexto o el tema manda. Predominan los datos, las fechas y los sustantivos.\n3. **Conativa o apelativa**: el receptor manda. Predominan los imperativos, los pronombres de segunda persona y las preguntas.\n4. **Fatica o de contacto**: la prueba de que el canal funciona. Es la funcion de los saludos y de la despedida.\n5. **Metalinguistica**: la lengua se usa para hablar de la lengua. Es la funcion del diccionario y de las reglas.\n\n> Pregunta de control: **quien manda en este texto**. Si mando el emisor, es emotiva. Si manda el receptor, es conativa.\n\n## Los tres rasgos que delatan cada funcion\n- **Emotiva**: primera persona, adjetivos, exclamaciones.\n- **Referencial**: sustantivos precisos, cifras, fechas, lugares.\n- **Conatica**: segunda persona, verbos en imperativo, interrogaciones.\n\n## Por que importa en el examen\nUn texto con datos y fechas es referencial aunque tenga adjetivos. Un texto con Imperativos es conativo aunque mencione un dato. La funcion la decide **lo que mas se repite**, no lo que aparece una vez.\n\n## La funcion mixta\nLos textos reales casi nunca son puros. Un aviso del colegio es conativo, porque pide algo, pero tambien es referencial, porque da la fecha. Se dice que es mixto y se nota cual de las dos manda.\n\nfigura:funciones-lenguaje | Cada funcion se delata por una clase de palabras: la que mas se repite manda",
          ejemplo: "Un texto dice: > Colemanos, la entrega de diplomas es el viernes 12 a las 9 de la manana en el patio central. Traigan su cedula.\n\n## Metodo 1: buscar los rasgos\n- Hay un imperativo: traigan.\n- Hay una segunda persona: ustedes, elijan la palabra usted.\n- Hay una fecha: el 12.\n\n## Metodo 2: decidir quien manda\n- La accion principal del texto es ordenar que traigan la cedula.\n- Las fechas solo urgency el aviso, no son el centro.\n- La funcion dominante es conativa.\n\n## Metodo 3: comprobar la funcion secundaria\n- La parte de la fecha y la hora es referencial.\n- Se dice que el texto es mixto, con predominio conativo.\n\n## Metodo 4: el contraste\nSi el texto fuera solo referencial, diria: la entrega de diplomas ocurrio el 12 de junio. Sin el imperativo, seria un informe del pasado, no una orden.\n\n## Conclusion\n- Conclusion: la funcion la define el elemento que se repite, y en este caso es la orden, no el dato.\n- Ojo: la funcion fatica puede estar en casi cualquier mensaje sin cambiar la funcion dominante.",
          consejo: "Para encontrar la funcion, haz dos columnas: una con lo que dice el emisor y otra con lo que hace el receptor. La columna mas larga indica la funcion dominante.",
        },
        {
          objetivo: "Analizar la oracion como unidad minima y separar con precision el sujeto del predicado, el paso que mas errores produce al escribir.",
          teoria: "## Que es una oracion\nUna **oracion** es un grupo de palabras con sentido completo que se apoya en si mismo. Es la unidad minima de la comunicacion porque ya no se puede dividir sin romper el sentido.\n\n## Los dos componentes obligatorios\n1. **El sujeto**: de quien o de que se habla.\n2. **El predicado**: lo que se dice del sujeto.\n\nToda oracion tiene las dos cosas, aunque la palabra que las marca no sea visible.\n\n> Regla de oro: si puedes preguntar **quien** o **que**, tienes el sujeto. Si puedes preguntar **que hace** o **como es**, tienes el predicado.\n\n## Los tres pasos para separar\n1. Localiza el verbo, contando sus formas conjugadas y los sustantivos que la acompanian.\n2. Pregunta quien hace el verbo. Ese es el sujeto.\n3. Lo que sobra, mas el verbo, es el predicado.\n\n## Sujeto simple y sujeto compuesto\n- **Simple**: un solo nucleo. *Los estudiantes escuchan.*\n- **Compuesto**: varios nucleos unidos por y, ni, o. *Los estudiantes y el profesor escuchan.*\n\n## Predicado nominal y verbal\n- **Nominal**: lleva un verbo copulativo, mas atributo. *El libro es interesante.*\n- **Verbal**: lleva un verbo de accion o estado. *El libro explica la teoria.*\n\n## Los subjects que confunden\n1. **El sujeto indire**: aparece dentro del predicado, tras una preposicion.\n2. **El sujeto pospuesto**: cuando la oracion se altera, el sujeto se coloca despues del verbo.\n3. **Las palabras de regimen**: nunca son sujeto.\n\n## La pregunta de comprobacion\nSustituye el sujeto por un uno o una ello. Si la oracion sigue teniendo sentido logico, era el sujeto.",
          ejemplo: "Oracion: Los estudiantes de segundo prepararon el informe.\n\n## Metodo 1: localizar el verbo\n- Hay un solo verbo: prepararon.\n- El sustantivo informe lo acompana, pero el verbo es prepararon.\n\n## Metodo 2: preguntar quien\n- Quien preparo el informe: los estudiantes.\n- Ese es el sujeto.\n\n## Metodo 3: separar el resto\n- Lo que sobra es de segundo y es el predicado.\n- Sujeto: los estudiantes de segundo. Predicado: prepararon el informe.\n\n## Metodo 4: comprobar por sustitucion\n- Ellos prepararon el informe.\n- La oracion tiene sentido, asi que los estudiantes era el sujeto.\n\n## Metodo 5: detectar el sujeto indirecto\n- Alguien dijo que prepararon el informe.\n- Aqui los estudiantes pasaron a ser sujeto indirecto, porque aparece tras la preposicion que.\n\n## Conclusion\n- Conclusion: el sujeto no es lo que esta al principio, sino lo que responde a la pregunta quien hace el verbo.\n- Ojo: el sujeto puede ir al final, y sigue siendo sujeto.",
          consejo: "Antes de escribir los signos de dos puntos, haz siempre la prueba del uno. Si al sustituir la frase inicial por uno la oracion se rompe, esa frase era el sujeto.",
        },
        {
          objetivo: "Reconocer el predicado verbal y el nominal por su verbo, y colocar correctamente los dos puntos de la oracion, que es donde se fallan las tildes.",
          teoria: "## Que es el predicado\nEl predicado es **todo lo que se dice del sujeto**, y se divide en dos partes:\n1. **El nucleo del predicado**: el verbo, que es lo unico imprescindible.\n2. **Los modificadores del predicado**: el resto, que completa el sentido.\n\nSi el nucleo es un verbo copulativo, el predicado es **nominal**. Si es cualquier otro verbo, es **verbal**.\n\n## Los verbos copulativos\nSeis verbos, y solo seis, pueden ser nucleo de un predicado nominal: **ser, estar, parecer, permanecer, quedar y resultar**.\nEstos verbos no expresan accion: enlazan el sujeto con una cualidad.\n\n## Nominal o verbal: la prueba\n- **Predicado nominal**: *La casa **es** grande.* El nucleo es **es**, que es copulativo. Lo que sigue, grande, es el **atributo**: dice como es la casa.\n- **Predicado verbal**: *La casa **fue construida** en 1920.* El nucleo es **construir**, que no es copulativo. Lo que sigue, en 1920, es un **complemento**: cuenta lo que le paso a la casa.\n\nLa diferencia esta en una sola pregunta: **la frase que acompana al verbo describe al sujeto o cuenta un suceso?**\n\n> Si describe al sujeto, es atributo y el predicado es nominal. Si cuenta un suceso, es complemento y el predicado es verbal.\n\n## Los dos puntos de la oracion\n1. **Los dos puntos de los signos** van antes de la coma y la exclamacion que cierran una enumeracion o una cita.\n2. **Los dos puntos de la puntuacion** separan un enunciado completo de su explicacion.\n\n## El error tipico\nSe escribe dos puntos antes de punto y coma. No es correcto: los dos puntos de puntuacion van seguidos de una oracion completa, y el punto y coma separa miembros de una misma oracion.\n\nfigura:predicado-nominal-verbal | Solo seis verbos pueden ser nucleo de un predicado nominal",
          ejemplo: "Oraciones para analizar: *La casa es grande. La casa fue construida en mil novecientos veinte.*\n\n## Metodo 1: buscar el verbo\n- En la primera oracion, el verbo es una forma de ser.\n- En la segunda, el verbo es construir, en forma pasiva.\n\n## Metodo 2: aplicar la prueba de quien\n- Quien es grande: la casa. Es el sujeto.\n- El nucleo es una forma de ser, que es copulativo, asi que el predicado es nominal. Grande es el atributo.\n- En mil novecientos veinte cuenta un suceso, no una cualidad de la casa. Por eso es complemento y el predicado es verbal.\n\n## Metodo 3: los dos puntos\nEn una enumeracion: Traer lapiz, cuaderno y calculadora. Aqui no hacen falta dos puntos.\nEn una explicacion: Solo hay una salida: la de la izquierda. Aqui si hacen falta, porque introducen una consecuencia o una aclaracion.\n\n## Metodo 4: el error a evitar\n- Mal: Traer lapiz, cuaderno; y calculadora.\n- Bien: Traer lapiz, cuaderno y calculadora.\n- Los dos puntos nunca van antes de un punto y coma.\n\n## Conclusion\n- Conclusion: el predicado se clasifica por su verbo, y la frase que lo acompana decide si es nominal o verbal.\n- Ojo: los dos verbos mas frecuentes, ser y estar, siempre hacen de nucleo nominal.",
          consejo: "Memoriza los seis verbos copulativos en una sola linea y veras la mitad de los ejercicios de predicado. Es la lista mas rentable del curso.",
        },
        {
          objetivo: "Distinguir las tres formas verbales del español y evitar el error de concordancia, que es el fallo mas frecuente al escribir.",
          teoria: "## Las tres formas del verbo\nTodo verbo tiene tres formas principales, y cada una cumple una funcion distinta:\n1. **Infinitivo**: comer, correr, escribir. No marca tiempo ni persona.\n2. **Presente de indicativo**: como, corro, escribo. Accion actual o habitual.\n3. **Pretérito y futuro**: comi, comere. Accion pasada o futura.\n\n## El error mas comun: la concordancia\nCuando el sujeto es un sustantivo, el verbo lleva su mismo tiempo y su mismo numero. El fallo aparece cuando el sustantivo ya trae un tiempo y el verbo trae otro, o cuando se repite el mismo tiempo dos veces.\n\n- Mal: los estudiantes estudian mucho ayer.\n- Bien: los estudiantes estudian mucho.\n- Bien: los estudiantes estudiaron mucho ayer.\n- Bien: los estudiantes que estudian llegan tarde.\n\n> Regla de oro: en una oracion simple, el tiempo va una sola vez.\n\n## Las dos formas de arreglarlo\n1. **Quitar el tiempo del sustantivo**: *los estudiantes que estudian llegan tarde.*\n2. **Quitar el tiempo del verbo**: *los estudiantes estudian mucho.*\n\nLas dos salidas son correctas. Lo que no se puede es dejar los dos tiempos.\n\n## Cuando si se repite el tiempo\n- **Numero propio con plural**: *Las bibliotecas son grandes.* Aqui el plural del sustantivo no es un tiempo, asi que se puede repetir la conjugacion.\n- **Verbos impersonales**: *Hubo dos estudiantes en el salon.* El verbo no concuerda con nada.\n- **Oraciones de relativo explicativo**: el tiempo puede ser distinto del de la principal.\n\n## Indicativo o subjuntivo\n- **Indicativo** afirma: un hecho que el emisor da por cierto.\n- **Subjuntivo** expresa deseo, duda, recomendacion o emocion: *Quiero que vengas.* *No creo que llueva.*\n\n> La diferencia clave: el indicativo afirma, el subjuntivo expresa deseo o posibilidad.",
          ejemplo: "Frase defectuosa: *Los estudiantes estudian mucho ayer.*\n\n## Metodo 1: localizar el problema\n- Hay un solo verbo: estudian, en presente.\n- Pero la palabra ayer obliga al preterito.\n- La oracion tiene dos marcas de tiempo: el presente del verbo y ayer.\n\n## Metodo 2: contar los sujetos\n- Solo hay un sujeto: los estudiantes.\n- Los estudiantes es plural, asi que el verbo va en plural.\n\n## Metodo 3: elegir una salida\n- Salida A, quitar ayer: *Los estudiantes estudian mucho.*\n- Salida B, cambiar el verbo a preterito: *Los estudiantes estudiaron mucho.*\n\n## Metodo 4: comprobar el modo\n- Si la frase es un deseo, el verbo va en subjuntivo: *Quiero que ellos estudien mucho.*\n- Si es una afirmacion, va en indicativo: *Los estudiantes estudian mucho.*\n\n## Metodo 5: la forma impersonal\n- *Hubo dos estudiantes en el salon.* El impersonal hubo no concuerda con el sujeto, y por eso admite cualquier numero.\n\n## Conclusion\n- Conclusion: la concordancia se rompe solo cuando la accion la hace otro sujeto distinto, o cuando el verbo es impersonal.\n- Ojo: es mas grave concordar mal que elegir entre indicativo y subjuntivo.",
          consejo: "Cuando tengas duda, aplica la regla de oro: un solo tiempo por oracion. Si aparecen dos verbos conjugados, casi siempre uno sobra.",
        },
        {
          objetivo: "Distinguir pronombres y adjetivos determinantes, y colocarlos en su lugar correcto sin duplicar informacion.",
          teoria: "## La diferencia basica\nUn **adjetivo determinante** acompana a un sustantivo y precisa quien es: *el libro, mi casa, tres mesas.* No se usa solo.\nUn **pronombre** sustituye a un sustantivo y se puede usar solo: *el leo, ella viene, estos son.*\n\n> Si la palabra necesita un sustantivo detras para tener sentido, es un determinante. Si puede ir sola, es pronombre.\n\n## Los pronombres personales\nSe dividen en dos series:\n1. **Sujetos**: yo, tu, el, ella, nosotros, vosotros, ellos, ellas. Se ponen antes del verbo.\n2. **Complementos**: me, te, lo, la, nos, os, les. Se ponen despues del verbo.\n\n## El pronombre lo\nEs el mas especial y el que mas se confunde. Puede ser:\n1. **Pronombre impersonal**: *Llueve mucho.* No se puede quitar.\n2. **Pronombre acusativo**: *Lo veo.*\n3. **Pronombre directo**: *Quiere comerlo.* Aqui lo sustituye al objeto y se junta con el verbo.\n\n## Los pronombres posesivos\n- **Adjetivos**: mi, tu, su, nuestro, vuestro, su. Siempre detras de un sustantivo: *mi casa, sus libros.* Nunca se usan solos.\n- **Sustantivos**: mio, tuyo, suyo, nuestro, vuestro, suyo. Siempre solos: *el mio, las tuyas.*\n\n> Este es el cambio que mas se olvida: mio se usa solo, y mi nunca se usa solo.\n\n## El error tipico\n- *Este es mio libro.* Debe ser *mi libro* o *este libro es mio*.\n- *Quiero que le den el mio.* Aqui mio va solo y es correcto.\n\n## Adjetivos y pronombres juntos\nCuando un determinante y un pronombre van juntos, el pronombre siempre va despues: *esta pagina, aquel maestro, nuestro pais.*",
          ejemplo: "Frase para analizar: *Quiero ese libro, pero el mio no es este.*\n\n## Metodo 1: localizar los determinantes\n- Quiero ese libro: ese es un determinante que se coloca antes del sustantivo.\n- La forma correcta es *mi libro*, porque mi es un determinante y se pega al sustantivo.\n\n## Metodo 2: comprobar el mio\n- En *el mio no es este*, mio va solo y precede al verbo. Es un pronombre posesivo sustantivo, y esta bien.\n- La regla se cumple: mio separado, mi junto.\n\n## Metodo 3: el error por confusion\n- La forma *quierothose libro* no existe: ese y libro no se pegan.\n- O se pone el determinante antes, *ese libro*, o se quita el determinante.\n\n## Metodo 4: la regla del orden\n- En *este libro*, el determinante este va antes del sustantivo.\n- En *el mio*, el pronombre va sin sustantivo.\n- Ninguno de los dos casos se contradice.\n\n## Conclusion\n- Conclusion: los determinantes se pegan al sustantivo y los posesivos en mio se separan. Ese es todo el truco.\n- Ojo: su es ambiguo, porque puede ser determinante o pronombre. El contexto dice cual es.",
          consejo: "Aprende la oposicion como una sola frase: mi con sustantivo, mio sin sustantivo. Con eso se resuelven casi todos los ejercicios de posesivos.",
        },
      ],
    },
    {
      lecciones: [
        {
          objetivo: "Decidir sin dudar cuando se escribe b y cuando se escribe v, aplicando las reglas del sonido y no la costumbre.",
          teoria: "## La idea de fondo\nEn español hay un solo sonidobilabial, el de la letra b. La letra v, en cambio, se pronuncia como una u con los labios, sin golpe. Por eso las dos letras suenan distinto.\n\n## Donde se escribe b\n1. **Antes de consonante**: bilabial, blindness, absurdo, técnica.\n2. **Despues de n o m**: una bicicleta, también, sombra.\n3. **En el pretérito imperfecto** de los verbos en ar, er e ir: amaba, comía, vivía.\n\n> La tercera regla es la trampa clásica. Se escribe b aunque suene como v, porque el imperfecto la pide siempre.\n\n## Donde se escribe v\n1. **Entre vocales**: vela, adversario, vehiculo.\n2. **En el presente, el futuro y los participios** de los verbos en ar, er e ir: hablo, como, viviré, hablar, comer, vivir.\n3. **En palabras cortas como cava, verano y vicinity**: no se doblan.\n\n## Donde no hay regla y hay que memorizar\n1. **El futuro irregular**: tendré, haré, podré, diré, saldré, vendré.\n2. **El imperativo de los verbos en ar, er e ir**: habla, come, vive.\n3. **El condicional irregular**: tendría, haría, podría.\n\n> Estos tres grupos son los únicos que no se deducen de ninguna regla.\n\n## La prueba de la boca\nCuando dudes, pronuncia la palabra tapándote los labios. Si al retirar la lengua notas un golpe de aire, es b. Si el aire sale continuo, es v.\n\n## El detalle fino\nLas palabras con be y las que empiezan por ve suenan igual: beso y verso, becerro y verbena. La diferencia es solo de escritura, no de sonido. Por eso el futuro irregular se escribe con ve y suena como el presente.",
          ejemplo: "Frase para analizar: *Las vacas bebieron agua y los becerros vivían tranquilos; habrá más leche.*\n\n## Metodo 1: revisar los imperfectos\n- bebieron lleva b, porque es imperfecto de beber.\n- vivían lleva b, porque es imperfecto de vivir.\n\n## Metodo 2: revisar los presentes\n- vacas lleva v, porque es presente de vacar.\n- becerros lleva v, porque es presente de becerar.\n\n## Metodo 3: revisar el futuro irregular\n- habrá lleva v, porque es futuro irregular de haber.\n\n## Metodo 4: aplicar la prueba de la boca\n- Pronunciando vacas y becerro con los labios tapados, el aire sale continuo. Por eso llevan v.\n- Pronunciando beber y vivir, el aire choca contra los labios. Por eso llevan b.\n\n## Metodo 5: el detalle fino\n- En habrá, el sonido es idéntico al de haber. Lo único que cambia es la escritura.\n\n## Conclusion\n- Conclusion: el imperfecto siempre lleva b, y el futuro irregular siempre lleva v. Con esas dos reglas se resuelve la mayor parte del ejercicio.\n- Ojo: escribía con b, pero escribo con v. El imperfecto explica la diferencia.",
          consejo: "Memoriza una sola frase con los cinco irregulares más usados: tendré, haré, podré, diré y vendré. Con eso cubres la mayoría de las dudas de futuro.",
        },
        {
          objetivo: "Distinguir s, c y z ante a, e, o, y evitar las excepciones que hacen fallar casi todos los ejercicios.",
          teoria: "## La idea de fondo\nHay dos sonidos que se escriben de tres maneras distintas, y la eleccion depende del sonido que suene:\n1. **Sonido fuerte**, como el de zapato. Se escribe c ante a, o, u, y z ante e, i.\n2. **Sonido suave**, como el de sapo. Se escribe s en todos los casos.\n\n> La pregunta que lo resuelve todo: **suena como zapato o suena como sapo**.\n\n## La regla concreta\n1. **z** ante e, i.\n2. **c** ante a, o, u.\n3. **s** en los demás casos.\n\n## Las excepciones que hay que saber\n1. El sonido fuerte ante e, i se escribe a veces con **c**: ciencia, ceiling. Nunca con z.\n2. El sonido suave ante e, i se escribe con **s**: sexo, mismo, sitio.\n3. La **s** final de palabra se escribe siempre con s: portable, tambien, despues.\n4. El plural de las palabras terminadas en **z** cambia la z por **ces**: luz, luces; razón, razones; pez, peces.\n\n> La excepción 4 cuesta más puntos, porque el singular y el plural se escriben de forma distinta.\n\n## Cuando la regla no decide\nAlgunas palabras hay que memorizarlas porque la regla no las explica. Son pocas, y conviene agruparlas:\n1. Las que llevan z ante a, o, u: zonas, gazpacho, bizcocho.\n2. Las que llevan s fuerte ante e, i: seria, siete, secured.\n\n## El metodo seguro\nCuando dudes entre s y c, escribe la palabra con s. Si al pronunciarla suena aspera, entonces es c. La s nunca suena fuerte, asi que si suena fuerte, no puede ser s.",
          ejemplo: "Frase para analizar: *Los cerdos viven cerca, pero las zanjas son más anchas que los otros calles de la región.*\n\n## Metodo 1: identificar los sonidos\n- cerdos suena suave, como sapo. Por eso lleva s.\n- viven suena suave, con v. Y con s al final, como todos los verbos en n.\n- zanjas suena fuerte, como zapato. Por eso lleva z ante a.\n- region suena fuerte, como zapato. Por eso lleva z ante i.\n\n## Metodo 2: aplicar el plural de la z\n- región en singular. En plural, regiones: la z se convierte en c.\n- calle en singular. En plural, calles: ya lleva ll.\n\n## Metodo 3: la excepcion de la c\n- ciencia suena fuerte ante i, pero se escribe con c y no con z.\n- Con z no existiría la palabra.\n\n## Metodo 4: comprobar la s final\n- viven lleva s al final, y es la forma correcta.\n- No se escribe vive.\n\n## Metodo 5: el metodo seguro\n- son empieza con s y suena suave. Correcto.\n- Si en lugar de son escribieras zon, sonaria fuerte y cambiaria el significado.\n\n## Conclusion\n- Conclusion: si suena suave, escribe s; si suena fuerte, escribe c ante a, o, u y z ante e, i.\n- Ojo:.region con s sonaría suave, y sería otra palabra. La z es obligatoria.",
          consejo: "No aprendas la regla sin las excepciones. Aprendelas juntas, porque en un examen la trampa siempre está en la excepción, nunca en la regla.",
        },
        {
          objetivo: "Distinguir la g de la j, y aplicar las reglas de la h, que son las de mayor exito en las pruebas de ortografia.",
          teoria: "## La idea de fondo\nLa g y la j suenan distinto, y la h casi siempre esta callada. Por eso las tres letras se distinguen facil si se sigue una sola idea: **cuando hace falta una letra de mas**.\n\n## Donde se escribe g\n1. **Ante e, i**, para que suene como j: gente, gigante, hielo.\n2. **En palabras que empiezan con geo-**: geografia, geologia.\n\n## Donde se escribe j\n1. **Siempre delante de a, o, u**: jamas,ajor, julio.\n2. **Detras de consonante**, cuando suena como j: reloj, trabajo.\n3. **En palabras que vienen del latin**: jinete, objeto.\n\n> La j nunca se escribe delante de e ni de i. Si delante de esas vocales hace falta un sonido como j, la letra correcta es g.\n\n## Las cuatro reglas de la h\n1. **h al principio de palabra**: hoy, hombre, hacer. Se escribe con h casi siempre.\n2. **h entre vocales**: la regla moderna es que no se escribe. Se escribe porhijo, no por hijo.\n3. **h despues de c**, en los sonidos de la ch:.charco, chico.\n4. **h muda**: se escribe pero no suena, como en hora, hombre y herir.\n\n## La diferencia entre ge y gue\n- **ge** suena como j: gelo, gente.\n- **gue** suena como g con e: guerrilla, guerra, hueste.\n\n> Para distinguirlas, mira lo que viene despues. Si la e se pronuncia, es gue. Si no se pronuncia, es ge.\n\n## Las excepciones de la h inicial\nCasi todas las palabras con h inicial llevan h. Las que no llevan h son pocas: hora, ostra, honor, y ocho palabras mas.",
          ejemplo: "Frase para analizar: *Hoy el hombre que hizo la guerra cuenta la historia a los jóvenes.*\n\n## Metodo 1: buscar las ge y las gue\n- No hay ninguna palabra con ge en esta frase.\n\n## Metodo 2: revisar las h iniciales\n- Hoy lleva h inicial.\n- hombre lleva h inicial.\n- historia lleva h inicial.\n\n## Metodo 3: revisar las j\n- jóvenes empieza con j, y la j va delante de e. Aqui hay una excepcion: la palabra es jóvenes, con tilde, y suena como jota.\n- Si se escribiera géFormal, la palabra no existiria.\n\n## Metodo 4: aplicar la regla de la h muda\n- En hora, la h se escribe pero no suena.\n- En hombre, la h se escribe pero no suena.\n\n## Conclusion\n- Conclusion: ge suena como j, gue suena como g con e, y la j nunca va delante de e ni de i.\n- Ojo: joven yacejOVENT, y por eso lleva j y no g.",
          consejo: "Para distinguir ge de gue, mira el final de la palabra. Si la e se oye, es gue; si no se oye, es ge. Esa es toda la diferencia.",
        },
        {
          objetivo: "Colocar la tilde general con seguridad, dividiendo las palabras en agudas, graves y esdrujulas segun la ultima sílaba.",
          teoria: "## La idea de fondo\nLa tilde general no depende del significado, sino de **donde cae el acento**. Por eso el primer paso es siempre el mismo: separar la palabra en sílabas y ver cual es la ultima.\n\n## Las tres clases\n1. **Agudas o llanas**: la ultima sílaba es la mas larga. Terminan en vocal, en n o en s.\n2. **Graves o agudas**: la ultima sílaba es la mas corta. Terminan en consonante distinta de n o s.\n3. **Esdrujulas**: el acento cae en la antepenultima sílaba. Siempre llevan tilde.\n\n> La pregunta clave: **las reglas dependen de como termina la palabra, no de como suena**.\n\n## Las cuatro reglas de la tilde general\n1. **Agudas que terminan en vocal, n o s**: llevan tilde. *cafe, jamon, crisis*.\n2. **Agudas que terminan en otra consonante**: no llevan tilde. *robot, movil, feliz*.\n3. **Graves que terminan en vocal, n o s**: no llevan tilde. *cancion, movil, analisis*.\n4. **Graves que terminan en otra consonante**: llevan tilde. *jardin, papel, util*.\n5. **Esdrujulas**: llevan tilde siempre. *telefono, camara, pagina*.\n\n## El atajo para no equivocarse\nSi la palabra termina en vocal, n o s, entonces la tilde depende de si es aguda o grave. Y hay un truco: si la palabra tiene mas de una sílaba, mira la segunda desde el final.\n\n- Si es la ultima, es aguda. Mira la regla 1.\n- Si es la penultima, es grave. Mira la regla 3.\n\n## Las palabras de una sílaba\nLas monosilabicas no llevan tilde general, salvo dos casos:\n- **guiones** y **fin**: la tilde se pone por diacritico, no por regla general.\n- **mas** y **solo**, cuando significa lo mismo que el adjetivo, tambien por diacritico.\n\n> La palabra **solo** lleva tilde cuando significa en solitario. Sin tilde, significa unicamente.\n\nfigura:tilde-general | Primero la ultima silaba, despues el final de la palabra",
          ejemplo: "Palabras para clasificar: *cafe, jamon, crisis, robot, movil, jardin, telefono, analisis*.\n\n## Metodo 1: separar en sílabas\n- cafe: ca-fe. La ultima sílaba es fe.\n- jamon: ja-mon. La ultima es mon.\n- crisis: cri-sis. La ultima es sis.\n- robot: ro-bot. La ultima es bot.\n- movil: mo-vil. La ultima es vil.\n- jardin: jar-din. La ultima es din.\n- telefono: te-le-fo-no. La ultima es no.\n\n## Metodo 2: ver como termina\n- cafe, jamon y crisis terminan en vocal o en n. Son agudas.\n- robot, movil y jardin terminan en consonante distinta de n o s. Son graves.\n- telefono lleva el acento en fo, que es la antepenultima. Es esdrujula.\n\n## Metodo 3: aplicar las reglas\n- cafe es aguda y termina en vocal. Lleva tilde: café.\n- jamon es agudo y termina en n. Lleva tilde: jamón.\n- crisis es aguda y termina en s. Lleva tilde: crisis.\n- robot es grave y termina en t. No lleva tilde: robot.\n- movil es grave y termina en l. No lleva tilde: móvil.\n- jardin es grave y termina en n. No lleva tilde: jardín.\n- telefono es esdrujula. Lleva tilde: teléfono.\n- analisis es esdrujula. Lleva tilde: análisis.\n\n## Conclusion\n- Conclusion: si termina en vocal, n o s, la tilde depende de si es aguda o grave. Si termina en otra consonante, se aplica la regla de grave o esdrujula.\n- Ojo: analisis se escribe con tilde aunque termine en s, porque es esdrujula, no aguda.",
          consejo: "Aprende la regla de las graves terminadas en vocal, n o s, porque es la que mas se olvida: cancion, movil y analisis NO llevan tilde, aunque sean largas.",
        },
        {
          objetivo: "Distinguir la tilde diacritica de la general, y usarla solo cuando cambia el significado de la palabra.",
          teoria: "## La idea de fondo\nLa tilde diacritica tiene un solo trabajo: **separar dos palabras que se escriben igual pero significa cosas distintas**. Si la palabra no tiene pareja que se le parezca, no lleva tilde.\n\n> La pregunta de control: **si quito la tilde, cambia el significado**. Si no cambia, la tilde sobra.\n\n## Los casos que hay que saber\n1. **tu** sin tilde es posesivo o demostrativo: *tu casa es mia*, *tu casa es grande*. **tu** con tilde es el pronombre: *tu comes bien*.\n2. **debe** obligation: *debe cien euros* frente a **debe** impersonal: *debe ser tarde*.\n3. **mas** cantidad: *trae mas* frente a **mas** adversativo: *mas bien*.\n4. **solo** adjetivo: *esta solo* frente a **solo** adverbio: *solo viene uno*.\n5. **aun** ancora: *aun no llega* frente a **aun** aunque: *aun asi, fallo*.\n6. **este** demostrativo frente a **este** posesivo: *este libro* frente a *este es mio*.\n\n## El caso de el y ese\n- **el** demostrativo: *Joven, mira el libro.*\n- **él** pronombre personal: *Joven, el lo hizo.*\nLa diferencia es la misma: si quitas la tilde y sigue significando lo mismo, no la lleva.\n\n## La palabra con doble funcion\nHay palabras que llevan tilde en un sentido y no en otro, con el mismo signo.\n- **solo** con tilde es adjetivo: *lo vi solo a el*.\n- **solo** sin tilde es adverbio: *lo vi solo*.\n\n> Cuando la palabra tiene las dos funciones, la tilde se pone en la que es adjetivo y se quita en la que es adverbio.\n\n## Lo que nunca lleva tilde\nLas palabras que no tienen una pareja parecida jamas llevan tilde diacritica. Si dudas entre dos palabras muy distintas, casi seguro que ninguna lleva tilde.",
          ejemplo: "Oraciones para analizar: *Tu casa esta ahi, pero tu no lo sabes. El nino debe salir, pero debe ser temprano.*\n\n## Metodo 1: separar las parejas\n- Hay dos pares: tu y tu, y debe y debe.\n\n## Metodo 2: probar los dos tu\n- Tu casa es mia: tu es posesivo y NO lleva tilde. Con tilde seria el pronombre tu, y la frase no tendria sentido.\n- Tu no lo sabes: tu es el pronombre y LLEVA tilde. Sin tilde seria el posesivo, y la frase tampoco tendria sentido.\n\n## Metodo 3: probar el primer debe\n- El nino debe salir: debe significa tener la obligacion de salir.\n- Debe ser temprano: debe es impersonal, y no lleva tilde.\n\n## Metodo 4: la prueba final\n- Si pongo tilde en Tu casa, la palabra pasa a ser el pronombre tu y la frase se rompe.\n- Si quito la tilde de debe ser temprano, no cambia nada, porque ya no lleva.\n\n## Conclusion\n- Conclusion: la tilde diacritica se pone solo en el miembro de la pareja que necesita separarse.\n- Ojo: las dos palabras se escriben igual, pero solo una lleva tilde en cada frase.",
          consejo: "No aprendas la tilde diacritica como una lista de reglas. Aprende pares, porque la tilde siempre se decide dentro de una pareja de dos palabras.",
        },
      ],
    },
    {
      lecciones: [
        {
          objetivo: "Construir un parrafo con una idea central clara, que es la unidad con la que se sostiene cualquier texto largo.",
          teoria: "## Que es un parrafo\nUn parrafo es un conjunto de oraciones que desarrollan **una sola idea**. Si en un parrafo hay dos ideas centrales, hay dos parrafos.\n\n## Las tres partes de un parrafo\n1. **La idea central**: la afirmacion que el parrafo quiere demostrar. Es la primera oración, y es la unica que no lleva conectores.\n2. **Las ideas secundarias**: las oraciones que apoyan la central con datos, ejemplos y razones.\n3. **La idea de cierre**: puede repetir la central con otras palabras o resumir el parrafo.\n\n> La prueba de que un parrafo es uno solo: si puedes poner un titulo que lo resuma en cinco palabras, es un parrafo. Y ese titulo es la idea central.\n\n## Los tres conectores que debes evitar\n1. **En medio del parrafo**: porque, por eso, ademas. La idea central no debe depender de un conector para entenderse.\n2. **Al principio**: la oracion central no necesita justificacion. Empieza por la afirmacion.\n3. **De mas**: un parrafo de mas de diez lineas suele tener dos ideas, y hay que partirlo.\n\n## La longitud util\nUn parrafo en un examen puede medir de tres a seis lineas. Si ocupa una pagina entera, casi siempre sobran repeticiones.\n\n## Como partir un parrafo\nCuando aparecen dos ideas centrales, se corta en el punto donde empieza la segunda. Cada mitad empieza con su propia oracion central.\n\n> Si tienes dudas, haz dos listas: una con lo que dice el parrafo y otra con lo que demuestra. La segunda tiene que tener un solo elemento. Si tiene mas, hay que partir.\n\nfigura:estructura-parrafo | Todo lo que va despues apoya la idea central",
          ejemplo: "Parrafo para analizar: *El agua es un recurso limitado. Solo hay una cantidad determined de agua dulce en el planeta, y esa cantidad no aumenta. Por eso, cuando la poblacion crece, el agua disponible por persona baja. Ademas, la contaminacion reduce la parte que se puede beber. Por esta razon, ahorrar agua es una responsabilidad de todos.*\n\n## Metodo 1: identificar la oracion central\n- La primera oracion dice que el agua es un recurso limitado. Esa es la idea central.\n\n## Metodo 2: revisar los conectores\n- Hay dos conectores: por eso y ademas.\n- La oracion central no depende de ellos, y por eso puede ir al principio.\n\n## Metodo 3: contar las ideas\n- Idea 1: el agua es limitada.\n- Idea 2: el agua por persona baja cuando crece la poblacion.\n- Idea 3: la contaminacion reduce el agua potable.\n- Hay tres ideas, asi que el texto necesita dos o tres parrafos.\n\n## Metodo 4: ver el cierre\n- La ultima oracion, ahorrar agua es responsabilidad de todos, es la idea de cierre. Repite la central con otras palabras.\n\n## Metodo 5: propone la division\n- Parrafo 1: el agua es limitada y por eso el agua por persona baja.\n- Parrafo 2: la contaminacion reduce el agua disponible y por eso hay que ahorrar.\n\n## Conclusion\n- Conclusion: un parrafo tiene una idea central, y todo lo demas la apoya.\n- Ojo: si la central lleva un conector como por eso, es que no es la central, porque todavia depende de algo anterior.",
          consejo: "Escribe siempre la oracion central antes que el resto. Si al final no la puedes quitar sin romper el parrafo, es que no era la central.",
        },
        {
          objetivo: "Unir las oraciones de un texto con cohesion y conectores, para que el lector vea las relaciones entre las ideas.",
          teoria: "## Que es la cohesion\nCohesion es la union entre las partes de un texto. Sin cohesion, las oraciones estan sueltas y el lector no entiende como se relacionan.\n\n## Los dos problemas tipicos\n1. **La palabra vacia**: *algo*, *cosa* o *eso*. No aporta nada.\n2. **La repeticion literal**: la misma palabra cinco veces en un parrafo.\n\n## Los cuatro recursos para evitar la repeticion\n1. **El sinonimo**: cambia la palabra pero no el sentido. *arbol* por *planta*.\n2. **El pronombre**: *el, la, este, ese, aquel*. Se usa cuando ya se sabe de quien se habla.\n3. **La elipsis**: se repite el verbo o el sujeto y se omite lo demas.\n4. **La palabra general**: *persona, cosa, animal, elemento*. Sirve para no repetir, pero solo si el texto no necesita el detalle.\n\n## Los tres fallos de cohesion que mas se ven\n1. **Un pronombre sin antecedente**: *llegaron y estaba cansado*. El que estaba cansado no se sabe.\n2. **Un sinonimo que cambia el significado**: si escribes *el coche* y luego *la moto*, ya no es el mismo.\n3. **Una palabra general que oculta lo importante**: *hablamos de las personas* es peor que *hablamos de los vecinos*.\n\n> La palabra general solo se usa en la ultima frase de un parrafo, para cerrar. En medio, siempre hay que nombrar.\n\n## La regla del conector\nUn conector no se pone por costumbre: se pone porque existe una relacion real entre las dos oraciones.\n- Si lo quito y la frase sigue entendiendose, el conector sobra.\n- Si lo quito y el sentido cambia, el conector era necesario.",
          ejemplo: "Parrafo para analizar: *Los vecinos hicieron ruido toda la tarde. Mi hermana estaba cansada. Por eso subio las ventanas.*\n\n## Metodo 1: buscar la palabra vacia\n- La palabra ruido aparece en la primera oracion y vuelve a aparecer en la tercera.\n\n## Metodo 2: buscar el pronombre sin antecedente\n- Mi hermana ya tiene antecedente, porque se sabe de quien se habla.\n- Si en su lugar se escribiera el, sin decir quien, la frase quedaria confusa.\n\n## Metodo 3: aplicar la elipsis\n- En vez de repetir, se puede escribir: los vecinos traian ruido toda la tarde; se oia hasta la calle.\n\n## Metodo 4: usar el sinonimo\n- Ruido se puede cambiar por algarabida, y suena mejor en la segunda oracion.\n\n## Metodo 5: revisar el conector\n- Por eso si es necesario: une la causa con la consecuencia. Si se quita, la ultima oracion queda suelta.\n\n## Conclusion\n- Conclusion: la cohesion se construye con pronombres que tienen antecedente claro, con sinonimos y con elipsis.\n- Ojo: cambiar ruido por algarabida solo vale si el ruido es de gente hablando. Si es ruido de trafico, seria incorrecto.",
          consejo: "Antes de entregar un texto, releelo buscando tres cosas: la palabra repetida, el pronombre sin antecedente y el conector innecesario. Esos tres cubren casi todos los fallos de cohesion.",
        },
        {
          objetivo: "Reconocer los cuatro generos textuales y elegir el registro adecuado, porque el mismo contenido cambia por completo segun el genero.",
          teoria: "## Que es un genero textual\nUn genero es una forma de organizar un texto que responde a una situacion concreta. Cambiar de genero cambia el tono, la estructura y hasta lo que se puede decir.\n\n## Los cuatro generos que hay que conocer\n1. **Narrativo**: cuenta hechos en el tiempo. Tiene personajes, un comienzo, un nudo y un final. Es el genero de la novela y del relato.\n2. **Descriptivo**: dice como es algo. No avanza en el tiempo, solo observa. Es el genero de la guia turistica y de la ficha tecnica.\n3. **Argumentativo**: expone una razon para convencer. Tiene tesis, argumentos y conclusion. Es el genero del ensayo y del editorial.\n4. **Expositivo**: explica un tema sin convencer a nadie. Define, clasifica y resume. Es el genero del texto escolar y del manual.\n\n## El dato que los delata\n- Si el texto **convence**, es argumentativo.\n- Si el texto **explica sin convencer**, es expositivo.\n- Si el texto **cuenta una sucesion de hechos**, es narrativo.\n- Si el texto **solo dice como es algo**, es descriptivo.\n\n> La confusion mas comun es entre argumentativo y expositivo. La diferencia es la intencion: el argumentativo quiere que cambies de opinion, el expositivo no.\n\n## Las cuatro partes del genero que mas se examina\n1. **Tesis**: la afirmacion que se va a defender.\n2. **Argumentos**: las razones que sostienen la tesis.\n3. **Prueba**: el dato que respalda cada argumento.\n4. **Conclusion**: el cierre, que no añade ideas nuevas.\n\n## El error tipico\nEmpezar el texto argumentativo con una definicion. Si la primera oracion es *el cambio climatico es un fenomeno*, el texto ya empieza a explicar en vez de argumentar, y la tesis se pierde.\n\n## Como se arregla\nLa tesis va en la primera oracion y no empieza con la palabra es. Empieza con una afirmacion: *el cambio climatico es la mayor amenaza del siglo*. Asi se distingue de una definicion.",
          ejemplo: "Cuatro textos para clasificar:\n\n## Texto 1\n*Maria fue al mercado a las ocho. Compro pan, volvio a las nueve y encontro a su hermana en la puerta. Esa mañana decidio no volver a salir.*\n\n- Clasificacion: narrativo.\n- Razon: cuenta hechos ordenados en el tiempo, con una persona y un lugar.\n\n## Texto 2\n*La torre tiene setenta metros de altura, fue construida en 1400 y su base mide veinte metros de lado.*\n\n- Clasificacion: descriptivo.\n- Razon: solo dice como es la torre. No hay hechos que avancen ni opinion.\n\n## Texto 3\n*El transporte publico reduce la contaminacion, es mas barato que el coche y evita el trafico. Por eso la ciudad deberia subir el precio del estacionamiento.*\n\n- Clasificacion: argumentativo.\n- Razon: da tres razones y termina pidiendo una accion. Quiere convencer.\n\n## Texto 4\n*La fotosintesis es el proceso por el cual las plantas convierten la luz en materia organica. Se realiza en los cloroplastos y libera oxigeno.*\n\n- Clasificacion: expositivo.\n- Razon: explica y define, pero no pide ninguna accion ni defiende una idea.\n\n## Conclusion\n- Conclusion: el mismo tema puede cambiar de genero segun la intencion. El transporte publico es descriptivo si se explica como funciona, y argumentativo si se defiende que conviene usarlo.\n- Ojo: el texto 4 podria ser argumentativo si terminara con una recomendacion. En cuanto pide una accion, cambia de genero.",
          consejo: "Antes de clasificar un texto, hazte una sola pregunta: pide el texto que el lector cambie algo. Si la respuesta es si, es argumentativo. Si es no, es expositivo.",
        },
        {
          objetivo: "Escribir un ensayo completo con tesis, argumentos, pruebas y conclusion, y evitar los dos errores que lo hacen fracasar.",
          teoria: "## Que es un ensayo\nUn ensayo es un texto argumentativo en el que una persona expone su opinion sobre un tema y la defiende con razones. Se escribe en primera persona y en lenguaje formal.\n\n## Las cuatro partes, en orden\n1. **Introduccion**: presenta el tema y anuncia la tesis. Ocupa un parrafo.\n2. **Desarrollo**: dos o tres argumentos, cada uno en su propio parrafo, con su prueba.\n3. **Conclusion**: resume lo dicho y añade una reflexion propia. No propone ideas nuevas.\n\n## La tesis, que es lo unico imprescindible\nLa tesis es **una sola oracion** que dice que piensas y por que. Tiene que ser una afirmacion, no un tema.\n\n- Tema: *el Handball en la escuela de secundaria*.\n- Tesis mala: *el Handball es un deporte.* Es una afirmacion, pero no dice nada que se pueda discutir.\n- Tesis buena: *el Handball es mas adecuado que el futbol para la escuela, porque se juega en equipo y el riesgo de lesion es menor.*\n\n> La diferencia entre tema y tesis es la diferencia entre el titulo y el primer parrafo. Si tu tesis se puede poner en un cartel, es demasiado vaga.\n\n## Los dos errores que hacen fracasar un ensayo\n1. **La definicion al principio**: empezar con *el deporte es una actividad fisica* no es argumentar. Empieza por la tesis.\n2. **La bibliografia como un bloque**: citar cinco autores al final no sustituye a tus argumentos. Las fuentes van dentro del texto, conectadas con tu idea.\n\n## La cita que si funciona\nSe cita con una frase breve, seguida de tu comentario. *Como dice el profesor: no se aprende jugando, se aprendiendo jugando.* Eso es una cita. Lo que no es una cita es pegar un parrafo entero de un libro sin decir por que lo pones.\n\n## El estilo\n- Primera persona: *creo, pienso, estimo*.\n- Lenguaje formal, sin coloquios.\n- Oraciones largas, con conectores: *sin embargo, por lo tanto, en consecuencia*.\n\n## La conclusion que suma\nUna conclusion debil solo repite. Una conclusion fuerte resume y ademas abre: *si esto es cierto, entonces la clase de educacion fisica deberia cambiar su plan.*",
          ejemplo: "Ensayo para analizar: *El deporte en la escuela*\n\n## Introduccion\n*Hoy el deporte ocupa menos tiempo en las escuelas que hace veinte anos. Sin embargo, la actividad fisica reduce el estres y mejora el rendimiento academico. Por eso creo que las horas de deporte deberian aumentar, y no reducirse.*\n\n## Desarrollo\n*En primer lugar, el deporte mejora la concentracion. Un estudiante que se mueve durante el dia llega mas despierto a la ultima hora de clase. Este efecto se ha observado en varios estudios sobre educacion fisica y salud escolar.*\n\n*En segundo lugar, el deporte enseña a trabajar en equipo. Un partido exige aceptar la decision del arbitro, esperar el turno y ayudar al que falla. Esas habilidades no se enseinan en ningun libro.*\n\n*En tercer lugar, reducir el deporte tiene un coste. Los estudios muestran que los minutos de actividad al dia bajan el riesgo de enfermedad en la etapa adulta. Ese coste aparece veinte años despues, y es cuando ya no se puede corregir.*\n\n## Conclusion\n*En resumen, el deporte no es un rato que se quita cuando hay presupuesto, sino una parte del aprendizaje. Si reducimos esas horas, estamos quitando algo que mas adelante va a costar mucho mas caro.*\n\n## Conclusion del analisis\n- La tesis aparece en el ultimo parrafo de la introduccion: las horas de deporte deberian aumentar.\n- Los tres argumentos se ordenan con en primer lugar, en segundo lugar y en tercer lugar.\n- Conclusion: la estructura esta completa y la tesis no se pierde en ningun momento.\n- Ojo: en el tercer argumento, la prueba es un dato. Si se quita la prueba, queda una opinion suelta.",
          consejo: "Escribe primero la tesis y luego los tres argumentos en una lista. Solo despues pasas a redactar. Si escribes de corrido, la tesis suele perderse en la tercera linea.",
        },
        {
          objetivo: "Corregir los seis errores de estilo mas frecuentes en un texto escrito, que son los que mas hacen bajar la nota.",
          teoria: "## Que es el estilo\nEl estilo es la manera de escribir. No se trata de complicar las frases, sino de quitar todo lo que estorba al lector.\n\n> La regla general: **lo que se puede quitar sin perder significado, se quita**.\n\n## Los seis errores que mas se repiten\n\n### 1. La frase demasiado larga\nSi una oracion tiene mas de treinta palabras, casi siempre son dos oraciones pegadas. Se parte en dos y el texto gana claridad.\n\n### 2. La voz pasiva innecesaria\nLa pasiva oculta quien hace la accion. *Se archivo el expediente* es mejor que *El expediente fue archivado por el secretario*.\n\n### 3. La palabra de mas\n- de mas, de menos, un intensificador repetido, el mismo, actual.\n- La palabra mas no se usa antes de un adjetivo: *no es muy alto*, nunca *es mas alto que bajo*.\n\n### 4. La repeticion innecesaria\nRepetir es correcto cuando aporta, y un error cuando no. La palabra clave se repite a proposito para marcar la idea; el resto se sustituye.\n\n### 5. El registro incorrecto\nUn texto formal no dice *cosas* ni *chaval*. Y un texto informal puede decir *vale* sin que sea un error.\n\n### 6. Los conectores de mas\nSe dice *ademas, por lo tanto, por consiguiente, asi pues* cuando solo hace falta *ademas* o *por lo tanto*.\n\n## El metodo de revision en tres pasos\n1. **Lee en voz alta.** Lo que suena raro, esta mal.\n2. **Busca las frases largas.** Partelas por donde haya una coma seguida de un verbo.\n3. **Busca las palabras de mas.** Relee mi:\n   - de mas, un intensificador repetido, el mismo, actual, etcetera.\n\n## El principio que resume todo\nEscribir bien es **dicho de otra manera**. No es escribir distinto, es escribir lo mismo con menos palabras.",
          ejemplo: "Texto para corregir: *La reunion fue convoinada por el Likes, y fue muy importante de verdad, y tambien fue muy larga, y ademas fue muy aburrida.*\n\n## Metodo 1: contar las palabras de la oracion\n- La oracion tiene mas de treinta palabras. Hay que partirla.\n\n## Metodo 2: cambiar la voz pasiva\n- *Fue convoinada por el Likes* pasa a *la convoino el Likes*.\n- El sustantivo *el Likes* es un nombre, y el nombre si importa: no se borra.\n\n## Metodo 3: quitar las palabras de mas\n- La repeticion del intensificador se elimina: queda *muy importante*.\n- *tambien* sobra: ya estamos en una lista de adjetivos.\n- *muy importante*, *muy larga* y *muy aburrida* se quedan en *importante, larga y aburrida*.\n\n## Metodo 4: quitar el conector de mas\n- Ademas ya introduce la ultima parte. No hace falta tambien.\n\n## Metodo 5: revisar el registro\n- No queda ningun coloquial.\n\n## Texto corregido\n*La reunion la convoco el Likes. Fue importante, larga y aburrida.*\n\n## Conclusion\n- Conclusion: el original decia lo mismo en veintidos palabras, y el texto corregido lo dice en once.\n- Ojo: quitar palabras nunca cambia el significado. Si al quitar una, el texto dice otra cosa, esa palabra era necesaria.",
          consejo: "Revisa tus textos en tres pasadas separadas: una solo buscando frases largas, otra solo palabras de mas y otra solo conectores. Si las mezclas, no ves nada.",
        },
      ],
    },
    {
      lecciones: [
        {
          objetivo: "Distinguir los generos literarios por sus rasgos propios, y reconocer en que genero esta escrito un fragmento.",
          teoria: "## Que es un genero literario\nUn genero literario es un conjunto de textos que comparten tres cosas: la **forma** en que estan escritos, el **tono** y lo que **esperan** del lector.\n\n## Los cuatro generos que se examinan\n\n### 1. Narrativo\nCuenta hechos. Usa la **voz del narrador** y el tiempo verbal en pasado. Hay personajes y hay un conflicto. Se puede resumir en una linea.\n- Subgeneros: cuento, novela, fabula, leyenda.\n\n### 2. Dramatico\nUn personaje habla. Todo esta en **dialogo** y en **accion**, y las acotaciones indican lo que no se dice. No hay narrador.\n- Subgeneros: comedia, tragedia, sainete, drama.\n\n### 3. Lirico\nUnicamente la voz de un yo que siente. Abunda la **imagen**, el ritmo y la emocion, y casi no hay argumento.\n- Subgeneros: poema, cancion, oda, elegia.\n\n### 4. Didactico\nQuiere transmitir un conocimiento. Usa la exposicion, la definicion y el ejemplo. Va dirigido a la razon, no a la emocion.\n- Subgeneros: ensayo, sermon, tratado,tract.\n\n> La pregunta de control: **quien esta hablando y por que medio**. Si hay alguien contando, es narrativo. Si hay alguien dialogando, es dramatico. Si solo hay un yo, es lirico.\n\n## Los tres rasgos que delatan el genero\n1. **La persona verbal**: el pasado delata al narrativo; el presente, al lirico.\n2. **La presencia del dialogue**: si hay dialogo, es dramatico.\n3. **La forma de la frase**: las frases largas y explicativas delatan al didactico; las cortas y quebradas, al lirico.\n\n## La confusion mas comun\nLa **fábula** se cuenta como narracion, pero tiene siempre una moraleja final. Si el texto termina con una leccion, es didactico aunque tenga animales y personajes.",
          ejemplo: "Cuatro fragmentos para clasificar:\n\n## Fragmento 1\n*Elmuchacho entro en la cocina a las siete. La madre estaba devantando el chocolate. Pregunto por el padre y ella no respondio. El muchacho entendio entonces que alguien se habia ido.*\n\n- Clasificacion: narrativo.\n- Razon: verbos en pasado, un personaje, un conflicto silencioso y una accion que el lector interpreta.\n\n## Fragmento 2\n*RAMON. No quiero ir.\nPADRE. No es una pregunta.\nRAMON. Entonces no voy.\n*Se oye un portazo.*\n\n- Clasificacion: dramatico.\n- Razon: todo esta en dialogo. La ultima linea es una acotacion, que indica una accion que no se ve.\n\n## Fragmento 3\n*Camino solo por calles de mayo\nque el agua se lleva\ny van golpeando mis zapatos.*\n\n- Clasificacion: lirico.\n- Razon: hay un yo, hay imagenes y no hay argumento. El tiempo verbal es el presente.\n\n## Fragmento 4\n*El teatro de commedia nacio en Italia en el siglo dieciseis. Sus autores fueron Lope de Vega y Calderon. Su finalidad era entretener y representar al pueblo.*\n\n- Clasificacion: didactico.\n- Razon: expone datos, da fechas y nombres. No hay personajes ni conflicto.\n\n## Conclusion\n- Conclusion: el genero se decide por quien habla, no por lo que cuenta.\n- Ojo: el fragmento 4 es didactico aunque hable de teatro. Hablar de un genero no convierte el texto en ese genero.",
          consejo: "Para identificar un genero, busca primero un dialogue. Si lo hay, es dramatico. Si no lo hay, busca una persona contando. Si la hay, es narrativo. Solo si no hay ninguna de las dos cosas, es lirico.",
        },
        {
          objetivo: "Reconocer las figuras literarias mas frecuentes, que son las que se piden identificar en casi todos los exámenes.",
          teoria: "## Que es una figura literaria\nEs una forma de decir algo que no es la forma normal. La mayoria tiene la misma estructura: un termino real, al que se llama **sentido propio**, y un uso figurado, que es el **sentido figurado**.\n\n- Sentido propio de puerto: el lugar donde se amarran barcos.\n- Sentido figurado: un punto de paso.\n\n> La pregunta clave: **el termino se puede tocar**. Si se puede tocar, es propio. Si no, es figurado.\n\n## Las figuras mas preguntadas\n\n### 1. Metafora\nRelacion directa entre dos cosas, sin ningun nexo.\n*Su corazon era un diamante.*\n**Que tiene**: comparacion, un termino con otro. Si hay un como o un como que, ya no es metafora sino comparacion.\n\n### 2. Comparacion o similitud\nEsta vez si lleva un nexo: como, cual, parece, semejante a.\n*Su pecho era como un diamante.*\n\n### 3. Hipersbole\nSe exagera para dar idea de la intensidad.\n*Estaba muerto de hambre.*\n**Que tiene**: una cantidad imposible, pero entendible.\n\n### 4. Metonimia\nSe cambia un termino por otro que esta relacionado.\n*Leo el Wein* en vez de *leo la guia del vino*.\n**Que tiene**: relacion de causa, materia, autor o contenido.\n\n### 5. Personificacion\nSe da acciones humanas a cosas que no las tienen.\n*El viento se quejaba.*\n**Que tiene**: un verbo de persona. El viento no se queja: el viento sopla.\n\n### 6. Anadiplosis\nSe repite el ultimo termino al principio de la frase siguiente.\n*Vino, vio y vencio.*\n**Que tiene**: la palabra que cierra una linea abre la siguiente.\n\n### 7. Epanadiplosis\nEs la inversa: se repite el primer termino al final de la frase.\n*Grande es el mar, y grande es mi cancion.*\n\n### 8. Aliteracion\nRepeticion de un mismo sonido consonante.\n*Rio rumoroso riega la ribera.*\n**Que tiene**: varias palabras seguidas con la misma letra inicial.\n\n### 9. Onomatopeya\nImita un sonido.\n*El reloj hacia tictac.*\n\n### 10. Antitesis\nSe oponen dos palabras o dos ideas en la misma frase.\n*Vive sin miedo, muere sin doctor.*\n\n### 11. Paradoja\nAfirmacion que parece contradiccion.\n*Se fue sin decir adios.*\n\n### 12. Ironia\nSe dice lo contrario de lo que se quiere decir.\n*Que service tan fino, la comida del hospital.*\n\n## La confusion mas comun\nLa ironia y la paradoja. En la **ironia** el autor dice lo contrario de lo que piensa. En la **paradoja** dice algo que parece imposible pero es cierto. La ironia necesita un tono, y la paradoja no.",
          ejemplo: "Oraciones para clasificar:\n\n## Oracion 1\n*El rio murmuraba entre las piedras.*\n- Figura: personificacion.\n- El rio no murmuraba: los piedras son mudas.\n\n## Oracion 2\n*Su mirada era de acero.*\n- Figura: metafora.\n- No hay nexo, y una mirada no se puede tocar. La ausencia de como confirma que es metafora y no comparacion.\n\n## Oracion 3\n*Me ha costado un rio de plata.*\n- Figura: hiperbole.\n- Nadie gasta un rio. Aqui el rio es una cantidad imposible.\n\n## Oracion 4\n*Bebo vino en la copa de Julian.*\n- Figura: metonimia.\n- La copa de Julian es un sinonimo de la copa, por la relacion de autor.\n\n## Oracion 5\n*El frio se colaba por las rendijas sin pedir permiso.*\n- Figura: personificacion.\n- Pedir permiso es una accion humana, y el frio no la tiene.\n\n## Conclusiones\n- Conclusion: las dos primeras oraciones se parecen, pero una es metafora y la otra personificacion. La diferencia esta en si hay un termino humano.\n- Ojo: si la oracion 2 tuviera como, *era como de acero*, seria comparacion y no metafora.",
          consejo: "Antes de bautizar una figura, haz la prueba del toque. Si el termino se puede tocar o pesar, es propio y no hay figura. Si no se puede, hay una figura y ahora solo hay que decidir cual.",
        },
        {
          objetivo: "Situar las tres corrientes y autores que mas se piden, y recordarlos por una imagen en vez de por una lista.",
          teoria: "## La idea de fondo\nLos autores no se aprenden por una lista. Se aprenden por lo que tienen en comun. Si sabes que hizo cada uno, ya sabes a que corriente pertenece.\n\n## Las tres corrientes del examen\n\n### 1. Realismo magico\nNace en America Latina en los años cincuenta. Mezcla lo real y lo fantastico sin explicar la mezcla: el narrador acepta lo imposible como cotidiano.\n- Autor: Gabriel Garcia Marquez.\n- Obra clave: *Cien años de soledad*.\n- Pista: un pueblo llamado Macondo, un pueblo entero que desaparece del mapa, y una maldicion sobre una familia.\n\n### 2. Boom latinoamericano\nNace en los años sesenta. Rompe con las novelas costumbristas y con las novelas de aventuras.\n- Autores: Mario Vargas Llosa, Julio Cortazar, Carlos Fuentes, Juan Carlos Onetti.\n- Obra clave: *La ciudad y los perros*.\n- Pista: el narrador ya no es fiable, el tiempo salta, y el protagonista busca algo que nunca alcanza.\n\n### 3. Narrativa policial\nNacida a finales del siglo diecinueve. Un crimen que hay que resolver, un detective y una solucion al final.\n- Autores: Jorge Luis Borges y Edgar Allan Poe. Poe escribio *Los crímenes de la calle Morgue*, el primer cuento policial.\n- Obra clave: *La muerte y la brujula*.\n- Pista: un crimen, un testigo, una solucion logica que se deduce.\n\n## El truco para memorizar\nNo memorices listas. Aprende **una obra, un autor y una pista** por cada corriente. Con tres fichas, no necesitas mas.\n\n1. Macondo desaparece del mapa: realismo magico, Garcia Marquez.\n2. Un laberinto de tiempo: boom latinoamericano, Vargas Llosa.\n3. Un crimen con solucion deducible: policial, Borges.\n\n## Las tres pistas que mas se preguntan\n1. **La obra**: de quien es y que argumento tiene.\n2. **El autor**: de que pais nacio y en que epoca escribio.\n3. **La corriente**: por que esa obra pertenece a esa corriente.\n\n> La tercera es la que mas cuesta. Para responderla hay que mirar la forma del texto, no solo su argumento. Un realista magico y un policial pueden contar lo mismo, pero se leen distinto.",
          ejemplo: "Tres preguntas tipicas de examen:\n\n## Pregunta 1\n*Cien años de soledad, de quien es y a que corriente pertenece.*\n- Autor: Gabriel Garcia Marquez.\n- Corriente: realismo magico.\n- Porque lo real y lo fantastico van juntos: nadie se sorprende de que un pueblo entero desaparezca del mapa.\n\n## Pregunta 2\n*De que pais es Garcia Marquez y que premio recibio.*\n- Es colombiano. Nacio en 1927 y recibio el Nobel de Literatura en 1982.\n\n## Pregunta 3\n*En que se diferencia el realismo magico de la novela policial.*\n- El realismo magico acepta lo imposible dentro de lo cotidiano y no lo explica.\n- La novela policial presenta lo imposible como un crimen que tiene que resolverse, y la resolucion es logica.\n\n## Metodo para responder sin memorizar\n- Pregunta 1: la obra te da el autor, y el autor te da la corriente.\n- Pregunta 2: la ficha del autor tiene pais y fecha.\n- Pregunta 3: la diferencia esta en la forma y en la intencion, no en el argumento.\n\n## Conclusiones\n- Conclusion: si reconoces una obra, ya tienes el autor y la corriente. Por eso una sola obra por corriente resuelve el examen entero.\n- Ojo: el Nobel de 1982 fue para Garcia Marquez. El de 2010 fue para Mario Vargas Llosa. No intercambies los años.",
          consejo: "Estudia por fichas, no por listas. Una ficha con obra, autor y una pista concreta se recuerda mejor que veinte nombres seguidos.",
        },
        {
          objetivo: "Analizar un poema por sus cuatro niveles, que es el orden en que el examen pide siempre la analisis.",
          teoria: "## La idea de fondo\nUn poema no se analiza buscando el tema escondido. Se analiza en **capas**: primero lo que dice, despues como lo dice, luego con que intencion y por ultimo que efecto produce. Ese es el orden que pide el examen.\n\n## Los cuatro niveles, en orden\n\n### 1. El contenido o tema\nQue dice el poema. Se responde con una frase: de que habla y que dice de eso.\n- No se busca el tema escondido. Se busca lo que el poema **afirma**.\n\n### 2. La forma\nComo esta escrito: el metro, la rima, la estructura de las estrofas y los recursos.\n- Tipo de poema: soneto, romance, haiku, verso libre.\n- Si hay rima, de que tipo: consonante o asonante.\n\n### 3. El recursos literarios\nQue figuras aparecen y en que palabras. Se citan literalmente, con su nombre.\n- *El rio dormia*: personificacion.\n- *Raton*: metonimia.\n\n### 4. La intencion y el efecto\nQue busca el poeta y que siente el lector. Aqui se cierra el analisis.\n\n> La pregunta que resume el metodo: **que dice, como lo dice, para que y que efecto causa**. Las cuatro respuestas, en ese orden.\n\n## Los tres datos que hay que mirar siempre\n1. **El titulo**: casi siempre resume la idea central. Se empieza por ahi.\n2. **El primer y el ultimo verso**: el primero plantea y el ultimo cierra.\n3. **Las palabras repetidas**: suelen ser la clave del poema entero.\n\n## La confusion mas comun\nConfundir el tema con el argumento. El tema es una afirmacion, no un asunto.\n- Asunto: el mar.\n- Tema: el mar no se puede relancejar.\nEl primero dice de que se habla. El segundo dice que piensa el poema. En un examen solo se acepta el segundo.\n\n## El truco de los cuatro niveles\nSi te piden el tema, no menciones figuras. Si te piden los recursos, no repitas el tema. Cada nivel tiene su propia respuesta, y mezclarlos es el error mas comun.\n\nfigura:analisis-poema-cuatro-niveles | El orden de los cuatro niveles no se puede cambiar",
          ejemplo: "Poema para analizar:\n\n*El mar\\ncuando se levanta\\nnadie sabe\\ndonde termina.\\n\\nLo que empieza\\ntermina, y el mar\\nsigue.*\n\n## Nivel 1: el tema\n- El poema habla del mar, y afirma que es algo que no se puede(rc) medir ni_(x) acotar.\n- Asunto: el mar.\n- Tema: el mar es ilimitado, y por eso no se puede medir ni delimitar.\n\n## Nivel 2: la forma\n- Trece versos.\n- Estructura: tres estrofas de cuatro versos.\n- No hay rima en el sentido estricto: se repite la palabra mar, y eso es una **anadiplosis** al final.\n\n## Nivel 3: los recursos\n- *Cuando se levanta*: el mar no se levanta por decision propia. Es personificacion.\n- *Nadie sabe donde termina*: la pregunta implicita es una anticipacion.\n- La repeticion de *el mar* al principio y al final es un recurso de estructura.\n\n## Nivel 4: la intencion y el efecto\n- El poeta quiere mostrar que hay cosas que no se pueden medir.\n- El efecto en el lector es de incomodidad, porque el poema no cierra la pregunta.\n\n## Conclusion\n- Conclusion: el tema se escribe con una afirmacion, no con un sustantivo.\n- Ojo: si escribes *el mar* como tema, el profesor va a decir que eso es el asunto y no el tema.\n- Conclusion 2: el orden de los cuatro niveles no se puede cambiar. Si empiezas por las figuras, ya no sabes que diras del tema.",
          consejo: "Escribe las cuatro respuestas en cuatro lineas separadas, con el titulo de cada nivel. Asi no mezclas el tema con las figuras y el trabajo queda ordenado.",
        },
        {
          objetivo: "Organizar el estudio de literatura con un metodo de cuatro pasos, para no acumular autores sin entenderlos.",
          teoria: "## La idea de fondo\nEstudiar literatura no es memorizar. Es aprender a hacer cuatro preguntas en orden a cualquier texto. Si dominas el metodo, puedes analizar algo que no habias leido.\n\n## Los cuatro pasos\n\n### 1. Leer dos veces\nLa primera vez, leyendo de corrido, para entender. La segunda vez, con lapiz, para marcar.\n- Primera pasada: de que va.\n- Segunda pasada: marco los recursos y las palabras que se repiten.\n\n### 2. Sacar los datos duros\nAntes de interpretar, hay que tener los hechos. Estos se escriben siempre igual:\n1. Que genero es.\n2. Quien lo escribio y cuando.\n3. De donde viene.\n4. Cual es el tema, en una frase.\n\n> Los datos duros se pueden aprender de memoria. La interpretacion se razona. No las mezcles.\n\n### 3. Separar lo que dice de lo que sugiere\n- Lo que **dice**: esta escrito, se puede copiar.\n- Lo que **sugiere**: es interpretacion, hay que justificarla con una cita.\n\nSi escribes *el poema es triste* sin citar nada, es una opinion. Si escribes *el poema es triste porque termina con la palabra se queda sola*, ya has justificado.\n\n### 4. Usar el mismo esquema siempre\nPara cualquier texto, el esquema es:\n1. Genero.\n2. Autor y epoca.\n3. Tema en una frase.\n4. Tres recursos con su cita.\n5. Intencion del autor.\n6. Efecto en el lector.\n\n## El fallo mas comun\nEmpezar por el tema antes de tener los datos duros. El resultado es una opinion sin base. Se lee, se anotan los datos, y solo entonces se interpreta.\n\n## Como estudiar para el examen\n1. Una ficha por obra, con los seis puntos del esquema.\n2. Un autor y una obra por corriente.\n3. Dos poems completos, no diez fragmentos sueltos.\n\n> Con dos poems completos y sus fichas, puedes responder cualquier pregunta de analisis. Con diez titulos sueltos, no puedes responder ninguna.",
          ejemplo: "Aplicamos los cuatro pasos a un texto: *La casa vacia* de un autor desconocido.\n\n## Paso 1: leer dos veces\n- Primera pasada: un hombre entra en una casa que ya no vive nadie, y se marcha sin tocar nada.\n- Segunda pasada: marco las repeticiones.\n\n## Paso 2: los datos duros\n1. Genero: narrativo, porque cuenta hechos en pasado.\n2. Autor y epoca: desconocido, finales del siglo XIX por el lenguaje.\n3. Tema: una persona no puede volver a su casa.\n\n## Paso 3: separar lo que dice de lo que sugiere\n- Lo que dice: *entro en una casa que ya no vivia nadie*.\n- Lo que sugiere: que se fue para siempre.\n\n## Paso 4: el esquema\n1. Genero: narrativo.\n2. Autor: desconocido, finales del siglo XIX.\n3. Tema: la casa perdida no se puede recuperar.\n4. Tres recursos:\n   - *ya no vivia nadie*: negacion, que refuerza el vacio.\n   - *sin tocar nada*: el verbo tocar sugiere contencion.\n   - *se marche*: verbo de movimiento, y se marcha en pasado.\n5. Intencion: mostrar que hay cosas que se pierden sin poder remediarlo.\n6. Efecto: incomodidad, porque el lector espera que el hombre se quede.\n\n## Conclusion\n- Conclusion: el mismo texto da muchos temas, pero solo uno encaja con los datos y con las citas.\n- Ojo: si escribes el tema antes de leer los recursos, eliges un tema y luego buscas citas que lo respalden. Eso es inventar, no analizar.",
          consejo: "Escribe siempre la ficha completa de un texto antes de pasar al siguiente. Diez fichas incompletas no sirven para nada; dos completas, si.",
        },
      ],
    },
  ],
};
