// ============================================================================
// Contenido profundo del curso de Razonamiento Verbal.
//
// Estos archivos PROFUNDIZAN la estructura de assets/js/cursos-data.js. La
// union es por posicion: modulos[0] es el primer modulo del curso y
// lecciones[3] es su cuarta leccion. Si aqui hay mas modulos o mas lecciones
// de las que existen, se anaden como nuevas y necesitan traer titulo.
// ============================================================================
CONTENIDO["razonamiento-verbal"] = {
  modulos: [
    {
      lecciones: [
        {
          objetivo: "Distinguir sinónimos exactos de palabras que solo se parecen, y elegir la alternativa que conserva el significado del texto.",
          teoria: "## Qué es un sinónimo\nUn sinónimo es una palabra con significado igual o muy cercano a otra. Sirve para evitar repeticiones sin perder precisión.\n-grande es sinónimo de enorme.\n- Empezar lo es de iniciar.\n\n## Sinónimo perfecto y sinónimo imperfecto\n- **Perfecto**: los dos significan exactamente lo mismo y son intercambiables.\n- **Imperfecto**: significan cosas parecidas pero no identicas, y cada uno aporta un matiz.\n\n> Esa diferencia de matiz es la clave del tema. En una prueba de comprensión, la alternativa que cambia el matiz también cambia el sentido del texto, y por eso es incorrecta aunque la palabra parezca equivalente.\n\n## Los falsos sinónimos\nGrupos de palabras que a menudo se confunden:\n- Vista y paisaje: no son lo mismo, uno es el aspecto visual y el otro el territorio.\n- Principio y comienzo: el principio es el fundamento, el comienzo es el inicio temporal.\n-}Aceptar y aprobar: no tienen el mismo significado legal.\n- Efecto y defecto: la diferencia está en la primera letra.\n\n## Registro\nDos palabras pueden ser sinónimas y aún asi no intercambiables, porque pertenecen a registros distintos.\n- Lo coloquial es más informal que lo neutro.\n- Lo académico es más formal que lo neutro.\n\n## Cuando buscar un sinónimo\nEn la lectura de textos, se busca un sinónimo cuando el examen **no** ofrece la palabra del texto y hay que encontrar cuál propuesta vale lo mismo. En ese caso hay que comparar el contexto, no solo el diccionario.",
          ejemplo: "En el texto se lee la palabra enorme. La alternativa correcta será una de estas:opuesto, titubeante, notable o dudoso.\n\n## Método 1: qué significa la palabra\n- Enorme quiere decir muy grande o de gran tamaño.\n\n## Método 2: descartar por significado\n- Titubeante significa que duda al hablar. No tiene relación con el tamaño.\n- Dudoso significa que es incierto o poco confiable. Tampoco.\n- Opuesto es una distracción: cambia las letras, no el significado.\n\n## Método 3: el candidato que queda\n- Notable significa digno de ser destacado, y aporta una connotación de singularidad, no de tamaño.\n\n## Método 4: la conclusión\n- Ninguna de las cuatro es un sinónimo de enorme.\n- En un examen real, esa pregunta estaría mal planteada, y la respuesta sería la más cercana: notable, entendida como digno de destacar.\n- Ojo: el ejercicio sirve para ver el método, no para memorizar la respuesta.\n\n- Conclusiones: hay que comparar el campo semántico completo, no buscar una palabra parecida en las letras.",
          consejo: "Antes de aceptar un sinónimo, prueba si podrías ponerlo en la frase y si el sentido se mantiene. Si la frase suena rara, la palabra no era sinónimo.",
        },
        {
          objetivo: "Reconocer antónimos de grado y de contradicción, y elegir la palabra que representa el contrario exacto del enunciado.",
          teoria: "## Los dos tipos de antónimos\n- **De grado**: hay una escala entre los dos extremos.\n  - Alto y bajo.\n  - Grande y pequeño.\n  - Antes y después.\n- **De contradicción**: los dos términos son extremos opuestos, sin punto medio posible.\n  - Si y no.\n  - Vivo y muerto.\n  - Todo y nada.\n\nEsta distinción importa porque algunos pares parecen graduales y no lo son.\n\n## Los falsos antónimos\nEstos grupos se confunden con frecuencia:\n- Efecto y defecto: no son opuestos, la diferencia está en la primera letra.\n- Principio y final: si se oponen, pero principio también significa fundamento.\n- Derivado y originario: dicen lo contrario de lo que sugiere el nombre.\n- Simpatico y antipatico: se oponen en la simpatia, no en la razon.\n\n> Un antónimo correcto no solo debe ser distinto, sino **imposible** de combinar con el mismo contexto. Si las dos palabras pueden vivir juntas en la misma frase, no son antónimos.\n\n## La prueba de la frase\nPara comprobar un antónimo, coloca las dos palabras en la misma oración:\n- Si el sentido se opone, el par es correcto.\n- Si la frase sigue teniendo sentido con las dos, no lo son.\n\nPor ejemplo, si y no pueden coexistir como respuestas a una misma pregunta. En cambió, grande y mediano sí pueden.\n\n## Antónimos contextuales\nEn un texto, el antónimo muchas veces es **inferido**, no se busca en el diccionario. Si el texto dice que las exportaciones subieron, el antónimo es que bajaron, aunque esa palabra no aparezca en la oración.",
          ejemplo: "El texto afirma que las exportaciones del país se incrementaron. Cuál de estas es el antónimo correcto: disminuyeron, se diversificaron, quedaron igual o se frenaron.\n\n## Método 1: qué dice el texto\n- Se incrementaron significa que crecieron.\n\n## Método 2: descartar por significado\n- Se diversificaron significa que se amplieron a otras áreas. Eso no contradice que hayan crecido.\n- Se frenaron significa que dejaron de crecer, y eso tampoco es lo contrario de haber crecido.\n- Quedaron igual significa que no cambiaron.\n\n## Método 3: el antónimo\n- Disminuyeron significa que bajaron, y es el contrario exacto de que crecieron.\n\n## Método 4: la prueba de la frase\n- Las exportaciones disminuyeron. El sentido se opone, así que el par es válido.\n- Conclusiones: disminuyeron es el antónimo correcto.\n\n- Ojo: si el texto hubiera dicho que se diversificaron, el antónimo habría sido que se concentraron en un solo rubro, y no que bajaron.",
          consejo: "Reemplaza la palabra del texto por la alternativa dentro de la misma oración. Si la frase queda absurda, es antónimo; si sigue funcionando, no lo es. Esa prueba vale más que cualquier lista memorizada.",
        },
        {
          objetivo: "Distinguir términos que se excluyen entre sí, porque pertenecen a campos semánticos que no pueden compartir una misma oración.",
          teoria: "## Qué son los términos excluidos\nDos términos son **excluidos** cuando no pueden aparecer juntos en una oración con sentido. Sus campos semánticos se contradicen.\n\nPiensa en categorías y no en palabras sueltas. Un color y un tamaño son categorías distintas: puedes nombrar las dos cosas por separado, pero un ejercicio que las excluye te pide tratar cada una como una categoría independiente.\n\n## Cómo se reconoce en un examen\nLa pregunta típica ofrece cuatro palabras y pide señalar la intrusa. El procedimiento es:\n1. Escribir una frase corta que reune tres de las cuatro palabras.\n2. Leer la frase en voz baja.\n3. Si algo suena absurdo, la palabra que sobra es la intrusa.\n\n## Campos semánticos\nCada palabra pertenece a un campo: personas, animales, plantas, objetos, lugares o acciones. Dos palabras de campos distintos y opuestos suelen ser excluidas entre si.\n\n> La diferencia con los antónimos es que aquí se prueba por contradicción entre categorías, y no por oposición de grado.\n\n## La trampa de la forma\nEn estos ejercicios hay palabras que se parecen en las letras pero no en el significado, y esa es justamente la trampa.\n\nUn error frecuente es escoger la palabra parecida por la forma. La forma no dice nada sobre el significado, y la mayoría de las veces lleva a la respuesta equivocada.",
          ejemplo: "Un ejercicio presenta cuatro palabras y pide señalar la intrusa. Tres de ellas nombran lugares donde se agrupan los animales, y la cuarta nombra un color.\n\n## Método 1: buscar el campo común\n- Las tres primeras pertenecen al mismo campo: lugares de agrupación animal.\n- La cuarta pertenece al campo de los colores.\n\n## Método 2: la prueba de la frase\n- Una frase que reune las tres primeras se puede decir sin esfuerzo.\n- La misma frase con la cuarta suena distinta a las otras.\n\n## Método 3: la conclusión\n- La intrusa es la cuarta palabra, porque no comparte el campo con las otras tres.\n- Conclusiones: el ejercicio pide reconocer el campo semántico, no la parecido de las letras.\n\n## Método 4: comprobar\n- La cuarta palabra no se parece en las letras a ninguna de las otras tres, así que no era una trampa de forma.\n- Es una palabra real, solo que del campo equivocado.\n- Ojo: esto distingue este ejercicio de los que usan palabras inventadas, donde la intrusa ni siquiera existe como palabra.",
          consejo: "Escribe siempre la frase de prueba antes de decidir. El ejercicio se resuelve en diez segundos con la frase, y en varios minutos cuando se intenta adivinar el campo semántico de memoria.",
        },
        {
          objetivo: "Completar series verbales de analogía, haciendo la relación entre los primeros términos y aplicándola a los últimos.",
          teoria: "## Qué es una serie verbal\nEs un ejercicio donde varios términos siguen una relación y hay que completar el siguiente. La relación no es de significado, sino de **posición dentro de la secuencia**.\n\n## Los pasos, siempre en este orden\n1. Escribe los términos en fila, con su número de orden.\n2. Mira la relación entre el término 1 y el 2.\n3. Mira si la misma relación aparece entre el 2 y el 3.\n4. Extiende la relación al término que falta.\n\n> Si la relación del 1 al 2 **no** es la misma que la del 2 al 3, la serie está mal planteada o hay un término mal puesto. No hay que forzar una relación distinta para cada par.\n\n## Las relaciones más frecuentes\n- **Aritmética**: la diferencia entre términos es constante. Se aplica la formula de sucesiones.\n- **Geométrica**: el cociente entre términos es constante.\n- **De alternancia**: se repite un ciclo de dos o tres términos.\n- **De suma de dígitos**: cada término se obtiene sumando las cifras del anterior.\n- **De lectura invertida**: los términos se leen al revés y asi forman otra serie.\n\n## Series de letras\nCuando los términos son letras, la posición en el alfabeto es el número que falta.\n- A son 1, B son 2, y asi sucesivamente hasta la Z, que son 26.\n- Convertir letra en número es el primer paso de cualquier serie alfabética.\n\n## El error típico\nTratar la serie de palabras como si el significado tuviera algo que ver. La relación es formal, no semántica.\n\nfigura:series-verbales | La serie sigue una regla: el distractor rompe el patrón",
          ejemplo: "Se pide completar la serie: 2, 4, 8, 16, x\n\n## Método 1: escribir la fila\n- Término 1 vale 2.\n- Término 2 vale 4.\n- Término 3 vale 8.\n- Término 4 vale 16.\n\n## Método 2: la relación entre los primeros\n- De 2 a 4 se multiplica por 2.\n\n## Método 3: comprobar que la relación se repite\n- De 4 a 8 se multiplica por 2.\n- De 8 a 16 se multiplica por 2.\n- La relación es constante, así que la serie es geométrica.\n\n## Método 4: extender\n- 16 * 2 = 32.\n- Conclusiones: el término que falta es 32.\n\n## Método 5: la vía alternativa\n- Si en cambió se hubieran restado 2 cada vez, la serie sería 20, 18, 16, x y el faltante sería 14.\n- Por eso hay que verificar la relación con dos pares antes de responder.",
          consejo: "Verifica la relación con dos pares, no con uno solo. Si el patrón se cumple en el par uno al dos y en el dos al tres, la respuesta casi siempre es correcta; si solo se cumple una vez, es una trampa.",
        },
        {
          objetivo: "Reconocer familias de palabras, deducir el significado de un término desconocido y distinguir la raíz de la terminación.",
          teoria: "## Qué es una familia de palabras\nEs un conjunto de palabras que comparten la misma raíz y que se forman añadiendo terminaciones distintas.\n- La raíz aporta el significado central.\n- La terminación precisa el género, el número o la función.\n\n## Para que sirve\nSirve para **deducir el significado de una palabra que no conoces**. Si reconoces la raíz, ya sabes de qué tema trata, aunque no sepas la definición exacta.\n\n## La terminación y el significado\n- Las terminaciones que indican acción suelen llevar -ar, -er o -ir.\n- Las que indican una persona que realiza la acción suelen llevar -dor, -ora, -ante o -ista.\n- Las que forman el nombre de la acción llevan -ción o -ción.\n\n## El error típico\nConfundir una palabra parecida con una palabra de la misma familia.\n- Parecidas en las letras no significa del mismo grupo.\n- Si al quitar la terminación no queda la misma raíz, no son familia.\n\n> Un mismo grupo de palabras puede tener sentidos muy distintos. Esa diferencia se llama **polisemia**, y es un tema aparte del que se ve aquí.\n\n## Cómo se usa en el examen\nCuando el examen presenta una palabra desconocida y pide su significado:\n1. Separa la raíz de la terminación.\n2. Piensa en otras palabras que tengan esa misma raíz.\n3. El significado buscado está en el tema de la raíz.\n4. Descarta las opciones que hablan de otro tema.\n\nEs el mismo método de los términos excluidos, aplicado a una sola palabra.",
          ejemplo: "La palabra desconocido es Proveedor, y se pide elegir su significado entre cuatro opciones.\n\n## Método 1: separar\n- La palabra termina en -edor.\n- La raíz probable es prov, que aparece en otras palabras del mismo grupo.\n\n## Método 2: reconocer la terminación\n- La terminación -edor indica una persona.\n- Entonces la palabra nombra a alguien, y no a una acción ni a un objeto.\n\n## Método 3: acotar por la raíz\n- La raíz se relaciona con una acción que alguien realiza\n- El tema es algo que se hace, y la persona es quien lo hace.\n\n## Método 4: eliminar\n- Descarta la opción que describe una acción, porque la palabra nombra a una persona.\n- Descarta la que describe un lugar, por la misma razon.\n\n## Método 5: la conclusión\n- La opción correcta es la que dice persona que ejerce la acción indicada por la raíz.\n- Conclusiones: el significado se dedujo por terminación más raíz, sin consultar el diccionario.",
          consejo: "En una palabra desconocida, empieza siempre por la terminación. Ella sola ya te dice si buscas una persona, una acción, un objeto o un lugar, y eso elimina la mitad de las alternativas.",
        },
      ],
    },
    {
      lecciones: [
        {
          objetivo: "Resolver analogías de palabras hallando la relación que une al primer par y comprobando que la misma relación se repita en el segundo.",
          teoria: "## Qué es una analogía\nUna analogía presenta dos pares y pide completar el segundo.\n- Par dado: A es a B.\n- Par por completar: C es a x.\n- La relación de A con B debe ser la misma que la de C con x.\n\n## Los cuatro pasos\n1. **Nombra la relación** del primer par con una sola palabra. Por ejemplo: causa, sinónimo, parte y todo, género y especie.\n2. **Aplica esa relación** a la segunda palabra del par dado.\n3. **Verifica** que el resultado tenga la misma categoría que A.\n4. Si la opción no cumple, descarta.\n\n> La analogía no se resuelve por parecido de letras ni por emoción del texto. Es una ecuación de relaciones, y se comprueba con la misma lógica que una ecuación común.\n\n## Relaciones que más aparecen\n- **Causa y efecto**.\n- **Sinónimo y sinónimo**, con distinta intensidad.\n- **Parte y todo**.\n- **Género y especie**: lo específico va antes de lo general.\n- **Profesión y lugar de trabajo**.\n- **Materia y objeto formado**.\n\n## La categoría como filtro\nUn filtro rápido y seguro: el resultado debe ser de la misma clase que la palabra del primer elemento.\n- Si A es una persona, x también debe ser una persona.\n- Si A es un lugar, x también.\n\n## Cuando hay más de una relación posible\nA veces dos relaciones sirven. En ese caso se elige la que **mantiene la categoría**, y si sigue la duda, la más simple y directa.\n\nfigura:analogia-relaciones | En una analogía se copia la relación del primer par, no el significado aislado",
          ejemplo: "Resolver la analogía: medicina es a enfermedad, Ohm es a ley.\n\n## Método 1: nombrar la relación\n- Medicina sirve para prevenir o tratar la enfermedad.\n- La relación del primer par es: medio usado frente a aquello que mide.\n\n## Método 2: aplicarla\n- Ohm es el nombre de una unidad de resistencia eléctrica.\n- La unidad de Ohm sirve para medir o expresar la resistencia eléctrica.\n\n## Método 3: verificar la categoría\n- La palabra que buscamos debe ser un concepto del mismo campo: la resistencia eléctrica.\n- Un Fenómeno no pertenece a ese campo.\n\n## Método 4: la conclusión\n- x es la palabra que nombra la resistencia eléctrica.\n- Conclusiones: la relación es la misma en los dos pares, un medio frente a lo que mide.\n\n## Método 5: comprobar por la vía inversa\n- Si la relación fuera al revés, la analogía buscaría un nombre de unidad a partir de una magnitud.\n- Como la magnitud eléctrica sí es un concepto y su unidad también, la lectura original es la correcta.",
          consejo: "Escribe la relación del primer par con una sola palabra antes de mirar las opciones. Con eso, la elección deja de ser una adivinanza y se vuelve una comprobación de que la relación se repite.",
        },
        {
          objetivo: "Usar conectores para marcar la relación entre ideas, elegir el conector según el tipo de relación y evitar las muletillas.",
          teoria: "## Para qué sirve un conector\nUn conector es una palabra o expresión que **señala la relación lógica** entre dos partes del texto. No es decoración: le dice al lector que sigue una adición, una causa, una oposición o una consecuencia.\n\n## Los cuatro grupos que debes dominar\n- **Adición**: las ideas se suman.\n  - conjunciones coordinantes como y, ni, sino, más, también.\n  - conectores de suma como además, asimismo, por otra parte.\n- **Causa y consecuencia**: una idea produce la otra.\n  - conectores de causa como porque, ya que, puesto que, dado que.\n  - conectores de consecuencia como por lo tanto, en consecuencia, luego.\n- **Oposición**: las ideas se contradicen o se limitan.\n  - pero, aunque, sin embargo, no obstante, mientras que.\n- **Orden y tiempo**: las ideas se ordenan en el discurso o en el calendario.\n  - primero, luego, finalmente, mientras, antes, después, entonces.\n\n## El error más caro\nUsar un conector que no corresponde a la relación real. Un porque dónde debía ir un aunque cambia por completo el sentido del texto, y en un examen eso significa una respuesta incorrecta.\n\n> Antes de elegir conector, pregúntate cuál es la relación: se suman, se oponen, una causa a la otra, o solo es orden. La pregunta decide el conector.\n\n## Muletillas\nFrases como por lo general, cabe destacar o es importante señalar que no aportan información. Ocupan lugar y retrasan la idea. En un texto corto de examen se eliminan sin perder sentido.\n\nfigura:conectores-relaciones | Cada grupo de conectores fija la relación entre las ideas",
          ejemplo: "Un texto dice: el transporte público se congestiona cada mañana. Ademas, los horarios se superponen con las entradas a las escuelas. Por eso lavalidacion del proyecto se Postergo.\n\n## Método 1: identificar la relación\n- La primera oración presenta un problema.\n- La segunda trae un dato adicional sobre el mismo problema.\n- La tercera explica una consecuencia de lo anterior.\n\n## Método 2: comprobar los conectores\n- Ademas marca adición, y la segunda oración suma información sobre el transporte. Correcto.\n- Por eso marca consecuencia, y la tercera oración es un resultado de las dos previas. Correcto.\n\n## Método 3: buscar el fallo\n- Si en la tercera oración apareciera sin embargo, el sentido cambiaría: pasaría de consecuencia a oposición.\n- El texto dirá que el proyecto se postergo **a pesar de** la congestion, que es lo contrario de lo que dice.\n\n## Método 4: la conclusión\n- Los dos conectores están bien usados.\n- El fallo estaría en introducir un conector de oposición dónde corresponde una consecuencia.\n- Conclusiones: el conector no es decorativo, cambiarlo cambia el significado.",
          consejo: "Escribe primero las ideas en dos columnas, una al lado de la otra, y luego pon el conector entre ambas. Si al leer la frase con el conector el sentido encaja, estaba bien elegido.",
        },
        {
          objetivo: "Organizar un texto con un plan de tres o cuatro partes, mantener la coherencia entre párrafos y cerrar con una conclusión que no introduce información nueva.",
          teoria: "## Qué es un plan de redacción\nEs el orden en que se presentan las ideas de un texto. Permite que el lector sepa dónde está cada cosa.\n\n## El plan de tres partes\nEs el más usado y el más fácil de defender.\n1. **Presentación**: se anuncia el tema y se replantea el problema central.\n2. **Desarrollo**: se explican los argumentos o los datos que sostienen la tesis.\n3. **Conclusión**: se cierra la idea y se deja una reflexión o una recomendación.\n\n## El plan de cuatro partes\nSe usa cuando hay dos ideas de igual peso.\n1. Introducción.\n2. Primer argumento.\n3. Segundo argumento.\n4. Conclusiones.\n\n## Reglas de coherencia\n- **Una idea por párrafo**. Si en un párrafo hay dos ideas, conviene separarlo.\n- **El primer párrafo no debe anticipar el desarrollo**, solo presentar el tema.\n- **Los conectores entre párrafos** deben dejar claro si hay adición, oposición o consecuencia.\n- **La conclusión no aporta datos nuevos**, porque si los aporta, todavía no era la conclusión.\n\n> El error clásico es cerrar con una idea que no se había mencionado. El lector siente que le cambiaron el tema al final, y con razon.\n\n## Cómo se revisa un plan\n1. Escribe el título de cada párrafo en una línea.\n2. Lee solo esos títulos, como si fueran un índice.\n3. Si la secuencia se entiende sin el desarrollo, el plan funciona.\n4. Si falta algo o sobra algo, el plan está desbalanceado.\n\nfigura:plan-redaccion | Tres bloques: introducción, desarrollo y conclusión",
          ejemplo: "Un ensayo de cuatro párrafos sobre el uso de Bicicletas en la ciudad tiene este problema: el último párrafo menciona el costo de mantenimiento, un dato que no aparecía en ninguno de los tres anteriores.\n\n## Método 1: listar los títulos\n- Párrafo 1: conviene usar más bicicletas en la ciudad.\n- Párrafo 2: reducen la contaminación del aire.\n- Párrafo 3: descongestionan las calles.\n- Párrafo 4: el mantenimiento cuesta dinero.\n\n## Método 2: leer solo los títulos\n- El salto entre el párrafo 3 y el 4 no se explica.\n- El lector no sabe por que aparece el costo de mantenimiento.\n\n## Método 3: decidir el arreglo\n- Si el costo es un argumento en contra, debe ir con los argumentos, no al final.\n- Si es un matiz a favor, debe ir dentro del desarrollo, con una frase que lo enlace.\n- Si de verdad cierra, entonces es una conclusión, y debería retomar los dos argumentos anteriores en vez de soltar un dato virgen.\n\n## Método 4: la conclusión\n- Un buen plan no obligaría a explicar por que el párrafo 4 existe.\n- Conclusiones: el problema no es el dato, es que llegó sin preparación.",
          consejo: "Antes de escribir el desarrollo, escribe en una línea el argumento de cada párrafo. Si no puedes, todavía no sabes que vas a decir, y el texto se va a desarmar solo.",
        },
        {
          objetivo: "Detectar la oración que sobra en un texto, justificar por que rompe la coherencia y comprobar que las demás forman un bloque único.",
          teoria: "## Qué es una oración eliminada\nEs una oración que el ejercicio propone quitar del texto. Casi siempre sobra **una sola**, y el trabajo está en justificar cuál.\n\n## Los cuatro motivos de sobra\n- **Rompe la unidad temática**: la oración habla de algo que no aparece en el resto.\n- **Rompe la cronología**: interrumpe el orden en que ocurren los hechos.\n- **Es una repetición**: repite lo que ya se dijo con otras palabras, sin aportar nada.\n- **Es una opinión impertinente**: mete el punto de vista personal del autor dónde el texto es informativo.\n\n## Cómo se comprueba\n1. **Lee el texto con la oración incluida.** Anota que dice.\n2. **Quita la oración.** Vuelve a leer.\n3. Si el texto sigue siendo coherente y completo, esa era la sobrante.\n4. Si al quitarla falta un dato, la oración era necesaria.\n\n> La prueba decisiva es la **redacción**: si al quitar la oración el texto queda más fluido, era la correcta. No basta con que parezca menos importante.\n\n## El error típico\nQuedarse con la oración más larga o la más llamativa. El ejercicio de eliminación suele usar una oración llana y redundante, que pasa desapercibida.\n\n## Cuando hay dos candidatas\nSi dos oraciones parecen sobrar, se aplica el criterio de la **cantidad de información**: sobra la que aporta menos información nueva, no la que más se parece a otra.",
          ejemplo: "Un texto sobre la historia de la imprenta tiene cuatro párrafos. El tercero dice: sin la imprenta, los libros se quedaban en los monasterios.\n\n## Método 1: qué aporta cada párrafo\n- Párrafo 1: la imprenta surge en Europa.\n- Párrafo 2: que permitía copiar muchos ejemplares.\n- Párrafo 3: sin ella, los libros solo circulaban entre los monasterios.\n- Párrafo 4: su efecto en la difusión del conocimiento.\n\n## Método 2: la prueba de la unidad\n- Los párrafos 1, 2 y 4 hablan de la imprenta y sus efectos.\n- El párrafo 3 también habla de ella, así que no rompe el tema.\n\n## Método 3: buscar el problema real\n- El problema del párrafo 3 es que está al final del desarrollo y repite la idea del párrafo 4: limiter la circulación es justamente lo que cambia con la imprenta.\n- Es una repetición, no una ruptura de tema.\n\n## Método 4: la conclusión\n- La oración sobrante es la del párrafo 3, por repetición.\n- Conclusiones: el texto sin ese párrafo mantiene su unidad y su orden lógico.\n\n- Ojo: si el párrafo 3 hablará sobre el costo de los libros, entonces si aporta un dato nuevo y habría que conservarlo.",
          consejo: "Elimina primero la oración que más te incómoda y lee el texto en voz alta. Si no se nota la falta, era la sobrante. La prueba de lectura en voz alta descubre los saltos de flujo mejor que el análisis.",
        },
        {
          objetivo: "Deducir el significado de una palabra a partir del contexto, usando pistas gramaticales y el sentido general del texto.",
          teoria: "## Qué es el término contextual\nEs el significado que una palabra adquiere en un texto concreto, distinto del que tiene en el diccionario.\n- La palabra tiene varios acepciones.\n- El contexto es lo que decide cuál de ellas vale.\n\n## Las cuatro pistas del contexto\n1. **Gramaticales**: la posición en la oración y la función sintáctica. Un sujeto y un verbo no pueden ser la misma palabra.\n2. **De sentido**: las palabras vecinas que comparten un campo temático.\n3. **De causa y efecto**: si una palabra explica o se explica.\n4. **De negación**: el contexto opuesto sirve para localizar el significado por contraste.\n\n## El procedimiento\n1. Rodea la palabra desconocida con las palabras que la acompañan.\n2. Anota cuales de ellas comparten tema con ella.\n3. Reemplaza la palabra desconocida por un sinónimo posible.\n4. Lee la oración completa. Si el sentido encaja, ese es el significado.\n5. Si ninguno encaja, vuelve al paso 2 con otra palabra.\n\n> El error típico es decidir por la palabra sola, sin leer la oración. Casi todas las palabras cambian de significado según quien las acompañe.\n\n## Polisemia\nSe llama **polisemia** a una palabra con varios significados relacionados entre si. No es un defecto, es la forma normal del lenguaje.\n\n## Cuando el texto no alcanza\nSi ninguna sustitución funciona, el problema está en el propio texto o en la pregunta. En un examen, eso casi siempre significa que se paso por alto una pista lejana.",
          ejemplo: "Frase del examen: el puerto era una condición indispensable para el comercio.\n\n## Método 1: las pistas gramaticales\n- La palabra desconocida ocupa la posición de sustantivo.\n- Va precedida por un artículo y seguida de una preposición.\n- Así que se descarta que sea un verbo o un adjetivo.\n\n## Método 2: el campo temático\n- La oración habla de comercio.\n- La palabra vecina es indispensable, que califica algo necesario.\n- Entonces la palabra desconocida nombra algo que era necesario para el comercio.\n\n## Método 3: probar sustituciones\n- Prueba condición indispensable: la frase queda sobre el puerto, que es exactamente lo que se quiere decir.\n- Prueba castigo indispensable: no tiene sentido con el comercio.\n- Prueba una palabra de trabajo: tampoco funciona.\n\n## Método 4: el descriptor\n- El puerto es indispensable para el comercio. La oración tiene sentido completo y coherente.\n\n## Método 5: la conclusión\n- El término contextual significa algo sin lo cual el comercio no sería posible.\n- Conclusiones: la pista decisiva fue el campo temático, no la gramática.\n\n- Ojo: si hubiéramos leído solo la palabra, habríamos respondido con el primer significado del diccionario, que es el error típico de este ejercicio.",
          consejo: "Escribe siempre la palabra desconocida junto a su sinónimo de prueba dentro de la oración. Si la frase suena natural, encontraste el significado; si suena rara, prueba otro.",
        },
      ],
    },
    {
      lecciones: [
        {
          objetivo: "Identificar la idea principal de un texto, separándola de los detalles, los ejemplos y las opiniones secundarias.",
          teoria: "## Qué es la idea principal\nEs la afirmación central que el texto quiere demostrar. Todo lo demás la apoya, la ilustra o la contradice.\n\n> Una idea principal no es un tema, es una afirmación. Decir que el texto trata de educación es un tema; decir que la educación publica no alcanza en las zonas rurales es una idea.\n\n## Los tres pasos para encontrarla\n1. **Resume cada párrafo en una línea.** Si no puedes, el párrafo todavía no está digerido.\n2. **Pregunta que tienen en común** esas líneas.\n3. **Redacta la idea principal** como una sola oración que contenga ese común.\n\n## Las cuatro trampas\n- **El título**: suele nombrar el tema, no la idea.\n- **La primera frase**: puede ser una introducción, no la tesis.\n- **Los ejemplos**: son ilustaciones, no la afirmación.\n- **La frase más larga**: la longitud no indica importancia.\n\n## Idea principal e idea secundaria\n- La **principal** es la que el texto no podría dejar de sostener.\n- Las **secundarias** apoyan la principal y se pueden quitar sin que el texto se caiga.\n\n## La prueba de la eliminación\nTapa el texto y deja solo la idea que propones. Pregúntate: si el resto del texto no existiera, quedaría claro de que se trata. Si la respuesta es si, esa es la idea principal.\n\nfigura:idea-principal | La idea principal es la que resumen todos los datos del texto",
          ejemplo: "Texto de cuatro párrafos sobre el agua: el primero describe la lluvia en la sierra, el segundo explica que los rios llevan esa agua al mar, el tercero cuenta que las ciudades crecieron sin control y el cuarto advierte que se esta agotando.\n\n## Método 1: una línea por párrafo\n- Párrafo 1: en la sierra llueve mucho.\n- Párrafo 2: esa agua baja por los rios hasta el mar.\n- Párrafo 3: las ciudades crecieron sin control.\n- Párrafo 4: el agua se está agotando.\n\n## Método 2: el común\n- Los párrafos 1 y 2 describen de donde viene el agua.\n- Los párrafos 3 y 4 describen su uso y su escasez.\n- El común no es la geografía ni el crecimiento: es la gestión del agua.\n\n## Método 3: la idea en una oración\n- El uso urbano del agua está creciendo más rápido que lo que la naturaleza puede reponer.\n\n## Método 4: eliminar los detalles\n- Si se borran los párrafos 1 y 2, la idea sigue sostenida por los párrafos 3 y 4.\n- Si se borra el párrafo 4, la idea desaparece, porque la advertencia es el remate.\n- Conclusiones: el cuarto párrafo es el que carga con la idea principal.\n\n- Ojo: el título del texto, si dice agua, es solo el tema y no sirve como respuesta.",
          consejo: "Empieza por el último párrafo. En la mayoría de los textos la idea principal se afirma o se advierte al final, y los primeros párrafos solo preparan el terreno.",
        },
        {
          objetivo: "Responder preguntas de comprensión literal localizando la información exacta en el texto, sin interpretar ni agregar nada.",
          teoria: "## Qué es la comprensión literal\nEs la lectura que recupera **lo que el texto dice de forma explícita**. No hay que interpretar,deducir ni suponer nada.\n- La respuesta está escrita en el texto.\n- A veces está escrita de forma exacta, con las mismas palabras.\n- A veces está expresada con otras palabras, pero sin ambigüedad.\n\n## Las cinco preguntas literales\n1. **Quien**_realiza la acción.\n2. **Que** ocurre o de que se trata.\n3. **Cuando** ocurre.\n4. **Donde** ocurre.\n5. **Por que** ocurre, solo si el texto lo explica de forma causal.\n\n## El método de localización\n1. Subraya en la pregunta las palabras clave.\n2. Busca en el texto la frase que contiene esas palabras.\n3. Copia la idea de esa frase, con las palabras del texto.\n4. Compara.\n\n> La trampa más común es responder con lo que uno sabe del tema, y no con lo que dice el texto. Un examen de comprensiónliteral se corrige contra el texto, no contra la realidad.\n\n## Preguntas con respuesta negativa\nCuando la pregunta se puede contestar con **no**, la respuesta es esa. Muchas preguntas están hechas para que se descarte la opción Obvia.\n\n## La diferencia con la inferencial\n- Literal: el texto dice A.\n- Inferencial: el texto dice A y B, y por eso se deduce C.\n\nSi tuviste que combinar dos frases para responder, ya no es literal.",
          ejemplo: "El texto dice: las acciones de 1939 alteraron las relaciones comerciales entre los países europeos, que hasta entonces dependían de rutas marítimas.\n\n## Pregunta: que altero las rutas marítimas\n- Es una pregunta literal de tipo que.\n\n## Método 1: palabras clave\n- La palabra clave es rutas.\n- La palabra clave es marítimas.\n\n## Método 2: localizar\n- La frase que lo dice es: que hasta entonces dependían de rutas marítimas.\n- El sujeto de esa frase es las relaciones comerciales.\n\n## Método 3: la respuesta\n- Lo que se vio afectado fueron las relaciones comerciales entre los países europeos.\n- No fueron las rutas las que se alteraron, sino las relaciones que dependían de ellas.\n\n## Método 4: la confusión que hay que evitar\n- Una opción puede decir que las rutas marítimas se cerraron. Eso no lo dice el texto.\n- El texto dice que las relaciones dependían de ellas, no que se cerraran.\n- Conclusiones: la respuesta literal es sobre las relaciones comerciales.\n\n- Ojo: si la pregunta hubiera pedido por que se alteraron las relaciones, la respuesta sería porque dependían de rutas que se afectaron, y ahi si habría que combinar dos ideas.",
          consejo: "Antes de elegir, verifica que cada palabra de la opción pueda señalarse con una frase del texto. La primera palabra que no puedas señalar es la que hace incorrecta a la opción.",
        },
        {
          objetivo: "Deducir lo que el texto no dice de forma explícita, combinando pistas para llegar a una conclusión correcta.",
          teoria: "## Qué es la comprensión inferencial\nEs la lectura que permite deducir una idea **a partir de lo que el texto sí dice**. La respuesta no está escrita, pero se deduce sin salirse del texto.\n\n## Las cuatro fuentes de inferencia\n1. **Causa y efecto**: si el texto dice A produce B, se puede inferir que sin A no habría B.\n2. **Generalización**: si el texto dice que todos los casos de un tipo tienen una característica, se puede aplicar a un caso nuevo.\n3. **Comparación**: si el texto dice que dos cosas se parecen en un punto, se puede suponer que se parecen en el mismo tipo de rasgo.\n4. **Propósito**: si el texto explica una causa, se puede inferir que el autor queria advertir sobre ella.\n\n> La inferencia tiene un limite: nunca puede contradecir al texto. Si la conclusión se opone a lo que el texto afirma, no es una inferencia, es un error.\n\n## El método de las tres preguntas\n1. Qué dice el texto de forma explícita.\n2. Qué se puede deducir de esos datos sin agregar información externa.\n3. Qué conclusión se sigue de combinar las dos.\n\nSi en el paso 2 necesitas un dato que no está en el texto, no es inferencia.\n\n## La trampa de la inferencia\nConfundir **lo que el texto dice** con **lo que uno quería que dijera**. Las opciones más tentadoras suelen ser las que afirman que el texto es claro y explícito. Si el texto no lo dice, la opción es incorrecta aunque sea razonable.\n\n## Indicios de una buena inferencia\n- La opción usa el lenguaje de la conclusión, no el de los datos sueltos.\n- Se apoya en dos o más partes del texto.\n- No contradice nada de lo explícito.",
          ejemplo: "El texto dice: desde 2019 el país aumentó sus reservas de gas. Al mismo tiempo, cerró dos plantas térmicas.\n\n## Método 1: lo explícito\n- Las reservas de gas aumentaron.\n- Se cerraron dos plantas térmicas.\n- Las dos cosas ocurrieron desde 2019.\n\n## Método 2: que se deduce\n- Las plantas térmicas se usan para generar electricidad con gas.\n- Si hay menos plantas y hay más reservas, el uso de gas debe bajar.\n\n## Método 3: la conclusión\n- Se deduce que la generación eléctrica del país cambia su composición hacia fuentes más limpias.\n- Esa conclusión no aparece en el texto, pero se apoya en dos datos explícitos.\n\n## Método 4: comprobar que no contradice\n- El texto no dice que el gas se uso menos.\n- Entonces la conclusión no lo contradice.\n- Conclusiones: es una inferencia válida.\n\n## Método 5: la opción que no lo es\n- Una opción que diga que las plantas se cerraron porque se acabo el gas contradiria el dato de que las reservas aumentaron.\n- Y otra que diga que el país dejo de usar gas por completo también excedería lo que el texto permite deducir.\n- Ojo: inferencia no es adivinanza. Solo se deduce lo que las pistas sostienen.",
          consejo: "Escribe la inferencia como una frase completa que incluya la palabra porque o por lo tanto. Si no puedes incluirla, no estabas infiriendo, estabas suponiendo.",
        },
        {
          objetivo: "Evaluar la fuerza de los argumentos de un texto, distinguir datos de opiniones y detectar los razonamientos que no se sostienen.",
          teoria: "## Qué es lectura crítica\nEs la lectura que **juzga** lo que el texto afirma, en lugar de solo entenderlo. No se trata de estar de acuerdo o en desacuerdo, sino de medir la solidez del razonamiento.\n\n## Los tres niveles de una afirmación\n1. **Hecho**: se puede verificar con datos o con fuentes. La tierra gira.\n2. **Opción**: refleja una postura y se puede discutir. La educación debería ser gratuita.\n3. **Suposición**: se da por cierta sin pruebas. La gente no quiere estudiar.\n\nUn texto mixto es correcto si los hechos son ciertos, y está bien construido si además las opiniones se apoyan en los hechos.\n\n## Las cuatro preguntas de la lectura crítica\n1. **Qué se afirma.** Separa los hechos de las opiniones.\n2. **Qué evidencia se presenta.** Busca el dato que respalda cada afirmación.\n3. **Qué queda fuera.** Detecta lo que el texto evita mencionar.\n4. **A quién favorece.** Una afirmación que solo se sostiene en un caso particular es débil.\n\n> Un texto puede ser verdad y aún asi estar mal argumentado. La verdad de una conclusión no rescata un razonamiento defectuoso.\n\n## Las tres marcas del razonamiento débil\n- **Generalizar sin base**: se concluye a partir de un caso aislado.\n- **Atribuir sin prueba**: asigna una causa sin mostrar el mecanismo.\n- **Omitir la contra**: presenta solo lo que apoya la tesis.\n\n## Cómo se responde en el examen\nLa pregunta suele pedir la valoración más fundamentada. La opción correcta es la que **menciona el problema concreto** del argumento, no la que solo expresa acuerdo o desacuerdo con el texto.",
          ejemplo: "Un texto afirma: como el transporte público es gratis en la capital y casi todos lo usan, la gratuidad es la causa de que la contaminación haya bajado.\n\n## Método 1: separar\n- Hecho: el transporte es gratis en la capital.\n- Hecho: casi todos lo usan.\n- Hecho: la contaminación bajo.\n- Opinión: la gratuidad causo la baja.\n\n## Método 2: buscar el apoyo\n- La afirmación causal dice que la gratuidad produjo el efecto.\n- Pero el texto no explica el mecanismo: podría ser que la baja se debiera al cierre de fabricas.\n\n## Método 3: que queda fuera\n- No se menciona que otras normas, como el uso de tapabocas, pudieron influenciar la calidad del aire.\n- La causa real queda abierta.\n\n## Método 4: la pregunta que hace débil el argumento\n- Dos hechos pueden aparecer juntos sin que uno cause el otro. Eso es una coincidencia, no una causa probada.\n\n## Método 5: la conclusión\n- El problema es que se afirma una causa basandose solo en una coincidencia temporal.\n- Conclusiones: la lectura crítica no dice que sea falso, sino que no está demostrado.",
          consejo: "Busca siempre la palabra que conecta los dos hechos. Si es porque, entonces o por lo tanto, el texto está causando o explicando. Ahi es donde hay que buscar la prueba que falta.",
        },
        {
          objetivo: "Comparar dos textos, identificar que estructura comparten y elegir la opción que mejor los diferencia.",
          teoria: "## Qué es un texto comparativo\nEs un ejercicio donde se presentan dos textos y se pide identificar sus **similitudes y diferencias**. El punto clave es que la respuesta suele estar en la **relación entre ambos**, y no en el análisis de uno solo.\n\n## Las cuatro relaciones posibles\n- **Coinciden**: los dos dicen lo mismo con distintas palabras.\n- **Se complementan**: uno aporta lo que al otro le falta.\n- **Se contradicen**: afirman cosas opuestas sobre el mismo asunto.\n- **Uno deepen al otro**: el segundo explica con más detalle lo que el primero plantea.\n\n## El método de las tres columnas\n1. Divide cada texto en sus ideas, no en sus párrafos.\n2. Escribe una idea por línea de la izquierda.\n3. Escribe las del segundo texto en la misma hoja.\n4. Une las ideas que se corresponden.\n\n1. **Idea 1**: está en el Texto A y también en el Texto B.\n2. **Idea 2**: está en el Texto A; en el Texto B falta.\n3. **Idea 3**: en el Texto A falta; está en el Texto B.\n\n## La estructura como pista\n- Si los dos textos tienen el mismo número de párrafos y la misma distribución, suelen coincidir en estructura.\n- Si uno tiene más partes que el otro, probablemente lo deepen.\n- Si tienen el mismo número de partes y contenidos opuestos, se contradicen.\n\n> El error típico es describir el primer texto con mucho detalle y decir poco del segundo. La pregunta pide la **relación**, y esa relación solo existe comparando.\n\n## La posición del autor\nUn texto suele presentar su postura en las conclusiones. Si los dos autores llegan a la misma conclusión por caminos distintos, son complementarios. Si llegan a conclusiones opuestas, se contradicen.",
          ejemplo: "Texto A: el uso del celu en el salon de clases reduce la concentración, porque cada notificación obliga a cambiar de tarea.\nTexto B: el mismo tema, sosteniendo que el problema no es el celu sino la falta de normas sobre su uso.\n\n## Método 1: las ideas de cada texto\n- A tiene dos ideas: el celu distrae, y la razon es la interrupción constante.\n- B tiene dos ideas: el celu no es el problema, y la causa real es la falta de normas.\n\n## Método 2: unirlos\n- Los dos textos tratan el mismo asunto y reconocen que hay un problema en el aula.\n- Pero identifican causas distintas.\n\n## Método 3: la relación que corresponde\n- No se contradicen, porque no afirman cosas opuestas del mismo hecho.\n- Tampoco coinciden, porque la explicación es diferente.\n- Si se complementan: uno describe el efecto y el otro desplaza la causa hacia las normas.\n\n## Método 4: comprobar la estructura\n- Los dos tienen dos ideas en el mismo orden.\n- La estructura es parecida y el contenido complementario.\n- Conclusiones: se complementan, y la diferencia está en la causa que cada uno propone.\n\n- Ojo: si el texto B hubiera dicho que el celu no afecta la concentración, entonces si se contradirian de forma directa.",
          consejo: "Escribe siempre las ideas de los dos textos en la misma hoja. En cuanto las pones una al lado de la otra, la relación aparece sola y desaparece la tentacion de describir en vez de comparar.",
        },
      ],
    },
    {
      lecciones: [
        {
          objetivo: "Leer textos extensos en examenes reales, dividirlos en bloques y responder sin quedarte sin tiempo.",
          teoria: "## El problema de los textos largos\nUn texto largo no se lee de una sola pasada en un examen. El error más común es empezar por el principio, leer con calma, quedarse sin tiempo y no responder nada.\n\nLa solución es invertir el orden: **primero las preguntas, después el texto**.\n\n## Los cuatro pasos\n1. **Lee las preguntas primero.** Anota que se te pide en cada una: un dato, una idea, una opinión o una valoración.\n2. **Clasifica las preguntas.** Las literales se responden buscando. Las críticas se responden después.\n3. **Lee el texto por bloques.** Busca la sección que corresponde a cada grupo de preguntas.\n4. **Responde de inmediato.** No dejes preguntas para el final.\n\n## Cuanto tiempo por pregunta\nSi el examen tiene 40 preguntas y 120 minutos, el promedio es 3 minutos por pregunta. Las críticas consumen el doble que las literales, así que conviene empezar por las fáciles.\n\n## Marcar el texto\n- **Subraya** los datos que aparecen en preguntas literales.\n- **Numera** los párrafos.\n- **Anota al margen** una palabra clave por párrafo.\n\n> El objetivo no es entenderlo todo. Es llegar a cada pregunta con la parte del texto que la responde ya localizada.\n\n## Cuando el tiempo se acaba\n- Deja las preguntas de opinión para el final, si son las más longas.\n- Nunca dejes en blanco: una respuesta aproximada con una palabra clave del texto puede tener puntos.\n- Si una pregunta no la puedes resolver, vuelve a la última que si resolviste y reinténtala con la lógica que te funcionó.",
          ejemplo: "Un examen tiene 40 preguntas sobre un texto de 1200 palabras, y solo 40 minutos para esa parte.\n\n## Método 1: el reparto\n- 40 minutos para 40 preguntas da 1 minuto por pregunta.\n- Es muy poco, así que el método de lectura completa es inviable.\n\n## Método 2: leer primero las preguntas\n- Al leerlas se detectan 12 literales, 20 inferenciales y 8 críticas.\n- Las 12 literales se pueden responder con una busqueda dirigida.\n\n## Método 3: el plan de trabajo\n- Bloque 1, unos 12 minutos: responder las 12 literales.\n- Bloque 2, unos 20 minutos: responder las 20 inferenciales.\n- Bloque 3, unos 8 minutos: las críticas.\n\n## Método 4: la re-revisión\n- Si al terminar sobran 4 minutos, se releen las críticas y se corrigen las respuestas más débiles.\n\n## Método 5: la conclusión\n- Con este plan se responden las 40 preguntas y se evita la sorpresa de quedarse a medias.\n- Con una lectura completa, es muy probable que solo se alcancen 15.\n\n- Ojo: el reparto de tiempo debe hacerse al principio, con calculadora si hace falta. Decidir sobre la marcha es lo que hace que se pierda el control.",
          consejo: "Escribe el tiempo disponible y divídelo entre el número de preguntas antes de abrir el examen. Un número concreto en la cabeza es lo único que impide que la lectura se coma todo el tiempo.",
        },
        {
          objetivo: "Descartar alternativas por técnicas de eliminación, sin necesidad de acertar la respuesta correcta a la primera.",
          teoria: "## La idea central\nEn un examen de cuatro o cinco opciones, acertar por eliminación es más seguro que intentar acertar por elección. Si descartas tres, la cuarta es correcta aunque no te sepa la respuesta de memoria.\n\n## Las cuatro técnicas de descarte\n\n### 1. Descarte por limite\nSi la opción dice más de lo que el texto sostiene, se descarta.\n- El texto dice que mejoro algo. Una opción que dice que desapareció excede lo permitido.\n\n### 2. Descarte por significa\nSi dos opciones dicen lo mismo, una de las dos es la correcta y la otra es una reformulación. La trampa suele estar en la que cambia un solo detalle.\n\n### 3. Descarte por oposición\nSi una opción es exactamente lo contrario de lo que dice el texto, es incorrecta. Es la técnica más rápida de todas.\n\n### 4. Descarte por\nSi una opción contradice algo que cualquiera sabe, se descarta sin necesidad de leer el texto.\n\n> Antes de leer todas las opciones, lee la pregunta. Si sabes la respuesta de memoria, marca la más parecida. Si no, empieza a descartar por los límites.\n\n## El orden de las técnicas\n1. Descarta por opuesta. Es lo más rápido y lo más seguro.\n2. Descarta por limite.\n3. Descarta por significa.\n4. Descarta por.\n\n## La trampa del tiempo\nLeer primero todas las opciones sin leer la pregunta es la causa más común de errores. La pregunta dice que se busca, y sin eso no hay criterio para descartar nada.\n\nfigura:eliminacion-orden | Se descarta de la técnica más rápida a la más lenta",
          ejemplo: "El texto dice: la nueva línea de transporte reduce un 20 por ciento el tiempo de viaje entre el norte y el centro.\nPregunta: que efecto tiene la nueva línea según el texto.\n\n## Método 1: leer la pregunta\n- Se pide el efecto, y según el texto.\n- La palabra clave es según el texto, así que no vale lo que yo sepa del tema.\n\n## Descarte 2: por limite\n- Una opción que diga que se duplica el tiempo de viaje se descarta.\n- El texto dice que se reduce, y una reducción no puede ser una duplicación.\n\n## Descarte 3: por significa\n- Hay dos opciones que dicen que el tiempo baja, pero una lo atribuye a menos transbordos y la otra a una mayor velocidad.\n- El texto no explica el mecanismo, así que solo una puede ser la que el texto sostiene.\n\n## Descarte 4: por oposición\n- Una opción que dice que el número de pasajeros cayo se descarta.\n- El texto no menciona el número de pasajeros.\n\n## La conclusión\n- Queda la opción que dice que el tiempo de viaje disminuye un 20 por ciento.\n- Conclusiones: se llegó por eliminación, sin necesitar leer el párrafo entero.",
          consejo: "Antes de mirar las opciones, tápalas con la mano y responde tu. Luego destapas y comparas. Si no hay ninguna parecida, la pregunta era de deducción y toca trabajar con el texto.",
        },
        {
          objetivo: "Aumentar la velocidad de lectura sin perder comprensión, aplicando técnicas de lectura rápida y controlando el tiempo.",
          teoria: "## Qué es la velocidad de lectura útil\nEs leer rápido **y entender lo mismo**. No se trata de pasar más páginas, sino de dejar de perder tiempo en partes del texto que no aportan.\n\n## Las cuatro zonas de un texto\n1. **Título y subtítulos**: la mayor información por palabra. Se leen siempre.\n2. **Primer y último párrafo**: ubican el texto completo.\n3. **Párrafos centrales**: se leen con detalle si la pregunta lo pide.\n4. **Ejemplos y listas**: se saltan si la pregunta es de opinión.\n\n> La técnica principal es **decidir que leer** antes de leer. Un buen lector pierde tiempo a propósito en la zona equivocada.\n\n## Los tres hábitos que ralentizan\n- **Subrayar cada línea**. Solo se subrayan los datos que aparecen en las preguntas.\n- **Volver atrás**. Si no entendiste una frase, sigue. Casi siempre el sentido se aclara después.\n- **Leer cada palabra**. Se leen los sustantivos y los verbos; los artículos se saltan.\n\n## El método del dedo o del cursor\nSeguir la lectura con un dedo o con el cursor evita los retrocesos, que son el mayor ladrón de tiempo. El ojo tiende a volver al principio de la línea sin que uno se dé cuenta.\n\n## Cómo medir el progreso\n- Marca el tiempo al empezar y al terminar.\n- Divide el número de palabras entre el tiempo.\n- Compara de un examen a otro, no con otras personas.\n\n## La relación con la comprensión\nUn lector lento no es necesariamente un mejor lector. Si se entiende menos, la velocidad no sirvió de nada. El objetivo es llegar a la respuesta correcta con el menor tiempo posible.\n\nfigura:lectura-zonas | No todas las partes del texto rinden lo mismo",
          ejemplo: "Un texto de 600 palabras tiene que responderse en 3 minutos. Eso son unas 200 palabras por minuto, una velocidad alcanzable.\n\n## Método 1: el reparto del tiempo\n- 30 segundos para el título y los subtítulos.\n- 30 segundos para el primer y el último párrafo.\n- 90 segundos para el resto.\n- 30 segundos para responder.\n\n## Método 2: leer por zonas\n- Los títulos y subtítulos ocupan 60 palabras y ya dicen que el texto trata de tres cosas.\n- Con eso se sabe que párrafo buscar para cada pregunta.\n\n## Método 3: evitar los desvíos\n- Los ejemplos del texto ocupan 150 palabras y no contienen ningún dato que pida el examen.\n- Saltarlos ahorra unos 45 segundos, casi la mitad del tiempo asignado.\n\n## Método 4: el resultado\n- Con la zona de títulos y los extremos se entiende la estructura.\n- Con el resto se responden las preguntas.\n- El tiempo total cabe en 3 minutos.\n\n## La conclusión\n- Conclusiones: el ahorro vino de decidir que no leer, no de leer más rápido.\n- Ojo: esto solo funciona si ya se sabe que busca. Sin eso, saltarse zonas es perder información.",
          consejo: "Empieza por el título, los subtítulos y el último párrafo. Con eso dejas de leer al azar, y leer al azar es la razon principal de que se pierda tiempo.",
        },
        {
          objetivo: "Reconocer las palabras que más se repiten en los examenes de comprensión y deducir su significado por el contexto.",
          teoria: "## Por que hay palabras clave\nUn examen no prueba el vocabulario completo de una lengua. Repite un grupo reducido de palabras que aparecen en todos los textos. Conocerlas cubre la mayor parte de las preguntas.\n\n## Los cuatro grupos que más se repiten\n1. **Palabras de causa y consecuencia**: el motivo por el que algo ocurre, y lo que se sigue de ello.\n2. **Palabras de contraste**: las que oponen dos ideas.\n3. **Palabras de cantidad y frecuencia**: lo que va más o menos, o lo que pasa a menudo.\n4. **Palabras de evaluación**: las que valoran de forma positiva o negativa.\n\n## Cómo se usa un grupo\n1. Si la palabra pertenece a un grupo, ya sabes que hace en la oración.\n2. Si es la palabra que falta, la función te dice que tipo de dato buscar: una causa, un contraste, una cantidad o un juicio.\n3. Con eso eliges la categoría de la respuesta.\n\n> Un mismo texto puede tener cuatro palabras desconocidas distintas. Si identificas la función de cada una antes de buscar su significado, la busqueda se vuelve mucho más dirigida.\n\n## Los tres casos\n- **Palabra polisémica**: mismo sonido, varios significados. El contexto resuelve.\n- **Palabra parasintética**: se forma con un prefijo y una raíz a la vez.\n- **Palabra culta**: viene del latín o del griego. Tiene equivalente en la lengua común.\n\n## Cómo estudiar las listas\nNo memorices diccionarios. Estudia por grupos y con ejemplos, porque el examen no pregunta por la palabra aislada sino por su función en una frase.",
          ejemplo: "Una oración dice: aunque la medida fue anunciada, no se aplico, por lo que el resultado se mantuvo.\n\n## Método 1: identificar las palabras clave\n- Hay tres: aunque, no se aplico y por lo que.\n\n## Método 2: clasificar cada una\n- Aunque pertenece al grupo de contraste: introduce una salvedad.\n- No se aplico es un hecho negativo, y pertenece al grupo de causa.\n- Por lo que pertenece al grupo de consecuencia.\n\n## Método 3: reconstruir la lógica\n- La medida se anuncio, pero no se aplico.\n- Como no se aplico, el resultado se mantuvo.\n- La cadena es: anuncio sin ejecución, y por eso nada cambió.\n\n## Método 4: la palabra difícil\n- La palabra desconocida es mantuve.\n- Por la función se deduce que significa permaneció sin cambios.\n\n## Método 5: comprobar\n- Si la medida no se aplico, el resultado se mantuvo. La frase tiene sentido completo.\n- Conclusiones: el significado se dedujo de la posición y del grupo, no de memoria.\n\n- Ojo: si se reemplaza mantuve por mejoro, la frase seguiría siendo gramatical pero falsa respecto al texto. La gramática no basta, hace falta la lógica.",
          consejo: "Aprende las palabras por grupo y no por lista alfabética. En el examen casi siempre sabes de antemano que función cumple la palabra, y con eso la mitad del significado ya esta.",
        },
        {
          objetivo: "Consolidar el vocabulario de examen con una segunda tanda de palabras, usando el mismo método de grupos y funciones.",
          teoria: "## Qué sigue al primer grupo\nEn la lección anterior se estudio el grupo de palabras que indica relación entre ideas. Ahora toca el segundo grupo, que es el más frecuente después de ese: las palabras que **describen características**.\n\n## El grupo de las características\nSon palabras que definen cómo es algo o cómo es alguien. Se dividen en cuatro subgrupos:\n1. **De tamaño**: indica cuanto mide o cuanto pesa.\n2. **De forma**: describen el aspecto exterior.\n3. **De estado**: dicen en qué condición está algo.\n4. **De duración**: indican cuanto tiempo dura.\n\n## Por que importa el subgrupo\nPorque un mismo sustantivo puede llevar varias características, y solo una encaja con el contexto.\n- Una palabra de tamaño no puede describir un estado.\n- Una palabra de duración responde a la pregunta cuánto tiempo, no a la pregunta cómo.\n\n> La pregunta de control es siempre la misma: **de que tipo es la característica que falta**. Si el texto dice cuanto pesa, solo sirven las palabras de tamaño.\n\n## Los tres casos\n- **Adjetivo**: califica directamente.\n- **Adverbio**: modifica la forma del verbo y suele indicar modo, no característica.\n- **Expresión sustantiva**: hace de adjetivo un grupo entero, y ahí está el error típico.\n\n## La trampa de las expresiones\nCuando el adjetivo se reemplaza por un grupo de palabras, es fácil cambiar el significado sin darse cuenta.\n- Reemplazar una palabra de tamaño por una de estado cambia lo que el texto afirma.\n\n## Método de estudio\nPara cada palabra, escribe un ejemplo propio con un dato numérico. Un ejemplo con números se recuerda mejor que uno abstracto y no se confunde con otros.",
          ejemplo: "Un texto dice: el nuevo material pesa 40 por ciento menos que el anterior, pero su precio es igual.\n\n## Método 1: clasificar lo que ya aparece\n- 40 por ciento menos es una característica de tamaño: el peso.\n- Precio igual es una característica de estado o de comparación: el costo no cambió.\n\n## Método 2: la palabra desconocida\n- La palabra desconocida es la que describe el material.\n- Por la función, debe ser una característica de forma, porque el peso ya está cubierto.\n\n## Método 3: comprobar la lógica\n- Si se dice que el material es más ligero que el anterior, la oración encaja con el 40 por ciento.\n- Si dijera que el material es más duro, la oración también sería gramatical, pero no aportaría nada sobre el dato dado.\n\n## Método 4: la conclusión\n- Conclusiones: la característica buscada debe hacer la comparación de peso que ya está en el texto.\n\n- Ojo: si la palabra desconocida es un sustantivo y no un adjetivo. En ese caso no describe una característica, sino que nombra el material, y la respuesta cambia por completo.",
          consejo: "Antes de elegir la palabra, escribe en el margen qué tipo de característica pide la oración: cuánto mide, cómo se ve, en qué estado esta o cuanto dura. Con esa palabra escrita, la elección se vuelve casi mecánica.",
        },
      ],
    },
  ],
};
